(function(){
  const CFG={
    med:{table:'medicines',button:'medImport',refresh:'medRefresh',required:['brand_name'],number:['units_per_pack','gst_percent','default_mrp','default_purchase_rate','default_selling_rate','minimum_stock','reorder_level','reorder_quantity','prescription_retention_months'],bool:['prescription_required','requires_register','prescription_retention_required','loose_sale_allowed','is_active'],allowed:['brand_name','generic_name','composition','strength','dosage_form','pack_size','primary_pack_unit','loose_unit','units_per_pack','package_unit','category','schedule','regulatory_schedule','storage_condition','hsn_code','barcode','gst_percent','default_mrp','default_purchase_rate','default_selling_rate','minimum_stock','reorder_level','reorder_quantity','manufacturer_id','manufacturer_name','prescription_required','requires_register','register_type','prescription_retention_required','prescription_retention_months','loose_sale_allowed','is_active'],template:['brand_name','generic_name','composition','strength','dosage_form','pack_size','manufacturer_name','category','schedule','hsn_code','barcode','gst_percent','default_mrp','default_purchase_rate','default_selling_rate','minimum_stock','reorder_level','reorder_quantity','units_per_pack','primary_pack_unit','loose_unit','loose_sale_allowed','prescription_required','is_active'],key:r=>[r.brand_name,r.generic_name,r.strength,r.pack_size].map(v=>String(v||'').trim().toLowerCase()).join('|')},
    mfr:{table:'manufacturers',button:'mfrImport',refresh:'mfrRefresh',required:['name'],number:[],bool:['is_active'],allowed:['name','short_name','contact_person','mobile','email','website','gst_number','address','notes','is_active'],template:['name','short_name','contact_person','mobile','email','website','gst_number','address','notes','is_active'],key:r=>String(r.name||'').trim().toLowerCase()},
    sup:{table:'suppliers',button:'supImport',refresh:'supRefresh',required:['name'],number:['credit_days','opening_balance'],bool:['is_active'],allowed:['name','supplier_code','contact_person','mobile','alternate_mobile','email','gstin','gst_number','state','state_code','drug_license_number','address_line_1','address_line_2','city','postal_code','credit_days','opening_balance','notes','is_active'],template:['name','supplier_code','contact_person','mobile','alternate_mobile','email','gstin','state','state_code','drug_license_number','address_line_1','address_line_2','city','postal_code','credit_days','opening_balance','notes','is_active'],key:r=>String(r.supplier_code||r.gstin||r.gst_number||r.mobile||r.name||'').trim().toLowerCase()},
    cus:{table:'customers',button:'cusImport',refresh:'cusRefresh',required:['full_name'],number:['age_years','opening_balance','credit_limit','loyalty_points'],bool:['is_active'],allowed:['full_name','customer_code','patient_identifier','mobile','email','date_of_birth','age_years','gender','customer_tax_type','gst_number','gstin','address','city','state','state_code','postal_code','opening_balance','credit_limit','loyalty_points','notes','is_active'],template:['full_name','customer_code','patient_identifier','mobile','email','date_of_birth','age_years','gender','customer_tax_type','gst_number','address','city','state','state_code','postal_code','opening_balance','credit_limit','loyalty_points','notes','is_active'],key:r=>String(r.customer_code||r.mobile||r.full_name||'').trim().toLowerCase()},
    doc:{table:'doctors',button:'docImport',refresh:'docRefresh',required:['full_name'],number:[],bool:['is_active'],allowed:['full_name','registration_number','qualification','speciality','mobile','email','clinic_name','clinic_address','city','state','postal_code','is_active'],template:['full_name','registration_number','qualification','speciality','mobile','email','clinic_name','clinic_address','city','state','postal_code','is_active'],key:r=>String(r.registration_number||[r.full_name,r.mobile].filter(Boolean).join('|')||'').trim().toLowerCase()}
  };
  const aliases={brand:'brand_name','brand name':'brand_name','generic':'generic_name','generic name':'generic_name','gst':'gst_percent','gst %':'gst_percent','gst rate':'gst_percent','mrp':'default_mrp','purchase rate':'default_purchase_rate','selling rate':'default_selling_rate','manufacturer':'manufacturer_name','short name':'short_name','contact':'contact_person','contact person':'contact_person','gst number':'gst_number','gstin':'gstin','supplier':'name','supplier name':'name','supplier code':'supplier_code','drug licence':'drug_license_number','drug license':'drug_license_number','credit days':'credit_days','opening balance':'opening_balance',customer:'full_name','customer name':'full_name','full name':'full_name','customer code':'customer_code','patient id':'patient_identifier','patient identifier':'patient_identifier','tax type':'customer_tax_type','gst customer type':'customer_tax_type','credit limit':'credit_limit','loyalty points':'loyalty_points',doctor:'full_name','doctor name':'full_name','registration':'registration_number','registration number':'registration_number','specialty':'speciality','clinic':'clinic_name','clinic name':'clinic_name','clinic address':'clinic_address',active:'is_active','mobile number':'mobile','phone':'mobile','postal code':'postal_code','pin code':'postal_code','pincode':'postal_code'};
  const cleanKey=v=>String(v||'').trim().toLowerCase().replace(/[_-]+/g,' ').replace(/\s+/g,' '),dbKey=v=>cleanKey(v).replace(/ /g,'_');
  const toBool=v=>{if(typeof v==='boolean')return v;const s=String(v??'').trim().toLowerCase();if(['false','0','no','n','inactive'].includes(s))return false;if(['true','1','yes','y','active'].includes(s))return true;return v===''||v==null?true:Boolean(v)};
  const toNumber=v=>{if(v===''||v==null)return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null};
  const toast=(m,t='success')=>window.MedvikaUI?.toast?.(m,t==='danger'?'error':t);
  function detect(){return Object.entries(CFG).find(([p])=>document.getElementById(p+'New'))||null}
  function ensureButtons(prefix,cfg){
    const anchor=document.getElementById(prefix+'Refresh')||document.getElementById(prefix+'New'),wrap=anchor?.closest('.master-head-actions');if(!wrap)return{};
    let template=document.getElementById(prefix+'Template');if(!template){template=document.createElement('button');template.id=prefix+'Template';template.type='button';template.textContent='Download Template';wrap.insertBefore(template,document.getElementById(prefix+'New')||null)}
    let imp=document.getElementById(cfg.button);if(!imp){imp=document.createElement('button');imp.id=cfg.button;imp.type='button';imp.textContent='Import Excel/CSV';wrap.insertBefore(imp,document.getElementById(prefix+'New')||null)}
    return{template,imp};
  }
  function downloadTemplate(prefix,cfg){
    if(!window.XLSX){toast('Spreadsheet tools are not available.','danger');return}
    const sample={};cfg.template.forEach(k=>sample[k]='');
    if('is_active' in sample)sample.is_active=true;if(prefix==='med'){sample.gst_percent=12;sample.units_per_pack=10;sample.primary_pack_unit='strip';sample.loose_sale_allowed=false;sample.prescription_required=false}if(prefix==='sup'){sample.credit_days=0;sample.opening_balance=0}if(prefix==='cus'){sample.customer_tax_type='B2C';sample.opening_balance=0;sample.credit_limit=0;sample.loyalty_points=0}
    const ws=XLSX.utils.json_to_sheet([sample],{header:cfg.template});ws['!cols']=cfg.template.map(k=>({wch:Math.max(14,k.length+2)}));
    const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Import Template');XLSX.writeFile(wb,`medvika-${cfg.table}-import-template.xlsx`);toast(`${cfg.table} template downloaded.`);
  }
  function normalizeHeaders(row,cfg,prefix){const out={};Object.entries(row||{}).forEach(([k,v])=>{const ck=cleanKey(k);let key=aliases[ck]||dbKey(k);if(prefix==='mfr'&&ck==='manufacturer name')key='name';if(prefix==='sup'&&key==='gst_number')key='gstin';if(prefix==='cus'&&key==='gstin')key='gst_number';if(cfg.allowed.includes(key))out[key]=v});return out}
  async function parseFile(file){if(!window.XLSX)throw new Error('Spreadsheet parser is not available.');const name=file.name.toLowerCase();if(name.endsWith('.csv')){const wb=XLSX.read(await file.text(),{type:'string'});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''})}
  async function importRows(prefix,cfg,rawRows){
    const profile=window.MedvikaAuth?.profile||{},pid=profile.pharmacy_id,uid=profile.user_id||null;if(!pid)throw new Error('Pharmacy profile not available.');if(!rawRows.length)throw new Error('No data rows found in the selected file.');
    let manufacturerMap=new Map();if(prefix==='med'){const {data,error}=await supabaseClient.from('manufacturers').select('id,name').eq('pharmacy_id',pid).limit(10000);if(error)throw error;manufacturerMap=new Map((data||[]).map(x=>[String(x.name||'').trim().toLowerCase(),x.id]))}
    const existingRes=await supabaseClient.from(cfg.table).select('*').eq('pharmacy_id',pid).limit(20000);if(existingRes.error)throw existingRes.error;const existing=new Set((existingRes.data||[]).map(cfg.key).filter(Boolean)),fileSeen=new Set(),valid=[],issues=[];
    rawRows.forEach((raw,i)=>{const r=normalizeHeaders(raw,cfg,prefix),rowNo=i+2;cfg.number.forEach(k=>{if(k in r)r[k]=toNumber(r[k])});cfg.bool.forEach(k=>{if(k in r)r[k]=toBool(r[k])});Object.keys(r).forEach(k=>{if(typeof r[k]==='string'){r[k]=r[k].trim();if(r[k]==='')r[k]=null}});if(prefix==='med'&&r.manufacturer_name){const id=manufacturerMap.get(String(r.manufacturer_name).toLowerCase());if(id)r.manufacturer_id=id;delete r.manufacturer_name}if(prefix==='sup'){const g=String(r.gstin||r.gst_number||'').trim().toUpperCase();if(g){r.gstin=g;r.gst_number=g}}if(prefix==='cus'){const g=String(r.gst_number||r.gstin||'').trim().toUpperCase();if(g){r.gst_number=g;r.gstin=g}if(!r.customer_tax_type)r.customer_tax_type=g?'B2B':'B2C'}if(prefix==='med'&&r.gst_percent!=null&&![0,5,12,18,28].includes(Number(r.gst_percent))){issues.push(`Row ${rowNo}: invalid GST rate`);return}const missing=cfg.required.filter(k=>r[k]==null||String(r[k]).trim()==='');if(missing.length){issues.push(`Row ${rowNo}: missing ${missing.join(', ')}`);return}const key=cfg.key(r);if(!key){issues.push(`Row ${rowNo}: could not determine duplicate key`);return}if(existing.has(key)||fileSeen.has(key)){issues.push(`Row ${rowNo}: duplicate skipped`);return}fileSeen.add(key);r.pharmacy_id=pid;r.is_active=r.is_active!==false;if(uid)r.created_by=uid;valid.push(r)});
    let imported=0,failed=0;for(let i=0;i<valid.length;i+=100){const batch=valid.slice(i,i+100),{error}=await supabaseClient.from(cfg.table).insert(batch);if(error){for(const row of batch){const one=await supabaseClient.from(cfg.table).insert(row);if(one.error){failed++;issues.push(`${cfg.table}: ${one.error.message}`)}else imported++}}else imported+=batch.length}return{imported,skipped:issues.length,failed,issues};
  }
  async function run(prefix,cfg,button){const input=document.createElement('input');input.type='file';input.accept='.csv,.xlsx,.xls';input.style.display='none';document.body.appendChild(input);input.onchange=async()=>{const file=input.files?.[0];if(!file){input.remove();return}const old=button.textContent;button.disabled=true;button.textContent='Importing...';try{const rows=await parseFile(file),result=await importRows(prefix,cfg,rows);toast(`Import complete: ${result.imported} imported, ${result.skipped} skipped${result.failed?`, ${result.failed} failed`:''}.`,result.failed?'warning':'success');if(result.issues.length)console.warn('Master import issues:',result.issues.slice(0,100));document.getElementById(cfg.refresh)?.click()}catch(e){console.error(e);toast(`Import failed: ${e.message}`,'danger')}finally{button.disabled=false;button.textContent=old;input.remove()}};input.click()}
  function attach(){const found=detect();if(!found)return;const [prefix,cfg]=found,{template,imp}=ensureButtons(prefix,cfg);if(template&&!template.dataset.templateBound){template.dataset.templateBound='1';template.onclick=()=>downloadTemplate(prefix,cfg)}if(imp&&!imp.dataset.importBound){imp.dataset.importBound='1';imp.onclick=()=>run(prefix,cfg,imp)}}
  const observer=new MutationObserver(()=>attach());observer.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',attach);setTimeout(attach,0);
})();