window.initDoctorsModule=async function(){
  const CFG={prefix:"doc",title:"Doctors",name:"Doctor",table:"doctors",order:"full_name",columns:[["Doctor","full_name"],["Registration","registration_number"],["Qualification","qualification"],["Speciality","speciality"],["Mobile","mobile"],["Clinic","clinic_name"],["Status","is_active"]],search:["full_name","registration_number","qualification","speciality","mobile","clinic_name","city","state"],fields:[["full_name","Doctor Name","text",true],["registration_number","Registration Number","text"],["qualification","Qualification","text"],["speciality","Speciality","text"],["mobile","Mobile","text"],["email","Email","email"],["clinic_name","Clinic Name","text"],["clinic_address","Clinic Address","textarea"],["city","City","text"],["state","State","text"],["postal_code","Postal Code","text"],["is_active","Active","checkbox"]]};
  const UI=window.MedvikaUI,$=id=>document.getElementById(id),P=CFG.prefix,toast=(m,t="success")=>UI.toast(m,t==="danger"?"error":t),profile=window.MedvikaAuth?.profile||{},pid=profile.pharmacy_id,uid=profile.user_id||null,safe=v=>UI.safe(v??""),norm=v=>String(v||"").trim().replace(/\s+/g," ").toLowerCase();let rows=[],editing=null;if(!pid){toast("Pharmacy profile not available.","danger");return}const E=s=>$(P+s);
  function display(v,key){if(key==="is_active")return v===false?"Inactive":"Active";return v==null||v===""?"—":String(v)}
  async function load(){const {data,error}=await supabaseClient.from(CFG.table).select("*").eq("pharmacy_id",pid).order(CFG.order,{ascending:true}).limit(20000);if(error)throw error;rows=data||[];render()}
  function render(){const q=E("Search").value.trim().toLowerCase(),status=E("Status").value,filtered=rows.filter(r=>{const txt=CFG.search.map(k=>r[k]).filter(v=>v!=null).join(" ").toLowerCase(),st=status==="active"?r.is_active!==false:status==="inactive"?r.is_active===false:true;return st&&(!q||txt.includes(q))});E("Count").textContent=`${filtered.length} record${filtered.length===1?"":"s"}`;E("Head").innerHTML="<tr>"+CFG.columns.map(c=>`<th>${safe(c[0])}</th>`).join("")+"<th>Actions</th></tr>";E("Body").innerHTML=filtered.length?filtered.map(r=>"<tr>"+CFG.columns.map(c=>`<td>${safe(display(r[c[1]],c[1]))}</td>`).join("")+`<td><button class="master-edit" data-id="${r.id}" type="button">Edit</button></td></tr>`).join(""):`<tr><td colspan="${CFG.columns.length+1}" class="empty">No records found.</td></tr>`;document.querySelectorAll(".master-edit").forEach(b=>b.onclick=()=>openEdit(b.dataset.id))}
  function inputHtml(f,row={}){const [key,label,type,required]=f,v=row[key];if(type==="checkbox")return `<label class="check-field"><input data-field="${key}" type="checkbox" ${v===false?"":"checked"}> ${safe(label)}</label>`;if(type==="textarea")return `<label>${safe(label)}${required?" *":""}<textarea data-field="${key}" rows="3" ${required?"required":""}>${safe(v??"")}</textarea></label>`;return `<label>${safe(label)}${required?" *":""}<input data-field="${key}" type="${type}" value="${safe(v??"")}" ${required?"required":""}></label>`}
  function openNew(){editing=null;E("FormTitle").textContent="New Doctor";E("Fields").innerHTML=CFG.fields.map(f=>inputHtml(f,{is_active:true})).join("");E("FormCard").hidden=false;E("FormCard").scrollIntoView({behavior:"smooth",block:"start"})}
  function openEdit(id){editing=rows.find(x=>x.id===id);if(!editing)return;E("FormTitle").textContent="Edit Doctor";E("Fields").innerHTML=CFG.fields.map(f=>inputHtml(f,editing)).join("");E("FormCard").hidden=false;E("FormCard").scrollIntoView({behavior:"smooth",block:"start"})}
  async function save(ev){ev.preventDefault();const payload={};CFG.fields.forEach(f=>{const [key,,type]=f,el=document.querySelector(`[data-field="${key}"]`);if(!el)return;payload[key]=type==="checkbox"?el.checked:(el.value===""?null:el.value.trim())});payload.full_name=String(payload.full_name||"").trim().replace(/\s+/g," ");if(!payload.full_name)throw new Error("Doctor Name is required.");payload.registration_number=payload.registration_number?String(payload.registration_number).trim().toUpperCase():null;payload.mobile=payload.mobile?String(payload.mobile).trim():null;if(payload.mobile&&!/^\+?[0-9]{10,15}$/.test(payload.mobile))throw new Error("Enter a valid doctor mobile number.");const others=rows.filter(r=>r.id!==editing?.id);if(payload.registration_number&&others.some(r=>norm(r.registration_number)===norm(payload.registration_number)))throw new Error(`Registration Number '${payload.registration_number}' is already linked to another doctor.`);if(!payload.registration_number&&payload.mobile&&others.some(r=>norm(r.full_name)===norm(payload.full_name)&&norm(r.mobile)===norm(payload.mobile)))throw new Error("A doctor with the same name and mobile already exists.");payload.pharmacy_id=pid;if(!editing&&uid)payload.created_by=uid;const btn=E("Save");btn.disabled=true;btn.textContent="Saving...";try{const q=editing?supabaseClient.from(CFG.table).update(payload).eq("id",editing.id).eq("pharmacy_id",pid):supabaseClient.from(CFG.table).insert(payload),{error}=await q;if(error)throw error;toast(`Doctor ${editing?"updated":"created"}.`);E("FormCard").hidden=true;editing=null;await load()}catch(e){toast(e.message,"danger")}finally{btn.disabled=false;btn.textContent="Save"}}
  E("New").onclick=openNew;E("Close").onclick=()=>{E("FormCard").hidden=true;editing=null};E("Form").onsubmit=save;E("Refresh").onclick=async()=>{try{await load();toast("Doctors refreshed.")}catch(e){toast(e.message,"danger")}};E("Search").oninput=render;E("Status").onchange=render;try{await load()}catch(e){toast(`Doctors could not load: ${e.message}`,"danger")}
};