window.initExpiryReportModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id;
 const n=v=>Number.isFinite(Number(v))?Number(v):0,m=v=>UI.money(n(v)),s=v=>UI.safe(v??"");let rows=[],visible=[];if(!pid){UI.toast("Pharmacy profile not available.","error");return;}const P="er",E=x=>$(P+x);
 function dateKey(value){if(!value)return "";const raw=String(value);if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return "";const y=d.getFullYear(),mo=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${mo}-${day}`;}
 function displayDate(value){const key=dateKey(value);if(!key)return "—";const [y,mo,d]=key.split("-");return `${d}/${mo}/${y}`;}
 function dates(){E("From").value="";E("To").value="";const key="medvikaDashboardFilter:expiry-report",requested=sessionStorage.getItem(key);if(requested){E("Filter").value=requested;sessionStorage.removeItem(key);}}
 async function load(){const r=await supabaseClient.from("medicine_batches").select("*,medicines(brand_name,generic_name,category)").eq("pharmacy_id",pid).gt("quantity_available",0).order("expiry_date",{ascending:true}).limit(50000);if(r.error)throw r.error;rows=r.data||[];apply();}
 function epochDay(key){if(!key)return null;const [y,mo,d]=key.split("-").map(Number);return Math.floor(Date.UTC(y,mo-1,d)/86400000);}
 function days(value){const target=epochDay(dateKey(value)),current=epochDay(dateKey(new Date()));return target===null||current===null?null:target-current;}
 function effectiveCost(x){return n(x.cost_rate??x.purchase_rate);}
 function statusOf(x){const d=days(x.expiry_date);return x.is_blocked?(d!==null&&d<0?"Blocked / Expired":"Blocked"):d===null?"No Expiry Date":d<0?"Expired":d<=30?"Critical":d<=90?"Near Expiry":"Valid";}
 function apply(){const flt=E("Filter").value,from=E("From").value,to=E("To").value,q=E("Search").value.trim().toLowerCase();visible=rows.filter(x=>{const key=dateKey(x.expiry_date),d=days(x.expiry_date),rangeOk=(!from||key>=from)&&(!to||key<=to),windowOk=flt==="expired"?d!==null&&d<0:flt?d!==null&&d>=0&&d<=Number(flt):true,txt=[x.medicines?.brand_name,x.medicines?.generic_name,x.batch_number,x.medicines?.category].join(" ").toLowerCase();return rangeOk&&windowOk&&(!q||txt.includes(q));});const qty=visible.reduce((a,x)=>a+n(x.quantity_available),0),cost=visible.reduce((a,x)=>a+n(x.quantity_available)*effectiveCost(x),0),near=visible.filter(x=>{const d=days(x.expiry_date);return d!==null&&d>=0&&d<=90;}).length;E("Sum1Label").textContent="Batches";E("Sum1").textContent=visible.length;E("Sum2Label").textContent=flt?"Qty at Risk":"Current Qty";E("Sum2").textContent=qty.toFixed(2).replace(/\.00$/,"");E("Sum3Label").textContent=flt?"Cost Exposure":"Current Stock Cost";E("Sum3").textContent=m(cost);E("Sum4Label").textContent="≤ 90 Days";E("Sum4").textContent=near;E("Count").textContent=`${visible.length} rows`;E("Head").innerHTML="<tr><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Days</th><th>Qty</th><th>Effective Cost</th><th>Cost Exposure</th><th>MRP</th><th>Status</th></tr>";E("Body").innerHTML=visible.length?visible.map(x=>{const d=days(x.expiry_date),status=statusOf(x);return `<tr><td><b>${s(x.medicines?.brand_name||"Medicine")}</b><br><small>${s(x.medicines?.generic_name||"")}</small></td><td>${s(x.batch_number)}</td><td>${displayDate(x.expiry_date)}</td><td>${d===null?"—":d}</td><td>${n(x.quantity_available)}</td><td>${m(effectiveCost(x))}</td><td>${m(n(x.quantity_available)*effectiveCost(x))}</td><td>${m(x.mrp)}</td><td>${s(status)}</td></tr>`}).join(""):'<tr><td colspan="9" class="empty">No expiry rows found.</td></tr>';}
 function csv(){if(!visible.length)return UI.toast("No expiry data to export.","warning");const esc=v=>`"${String(v??"").replaceAll('"','""')}"`,lines=[["Medicine","Generic","Batch","Expiry","Days","Qty","Purchase Rate","Cost Exposure","MRP","Status"].map(esc).join(","),...visible.map(x=>[x.medicines?.brand_name,x.medicines?.generic_name,x.batch_number,displayDate(x.expiry_date),days(x.expiry_date),x.quantity_available,effectiveCost(x),(n(x.quantity_available)*effectiveCost(x)).toFixed(2),x.mrp,statusOf(x)].map(esc).join(","))];const b=new Blob([lines.join("\n")],{type:"text/csv"}),a=document.createElement("a"),u=URL.createObjectURL(b);a.href=u;a.download="medvika-expiry-report.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);}
 dates();E("Filter").onchange=apply;E("Search").oninput=apply;E("Apply").onclick=apply;E("Export").onclick=csv;E("Refresh").onclick=()=>load().catch(e=>UI.toast(e.message,"error"));try{await load();}catch(e){UI.toast(e.message,"error");}
};