window.initGstr3bModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id;
 const n=v=>Number.isFinite(Number(v))?Number(v):0,m=v=>UI.money(n(v)),zero=()=>({taxable:0,igst:0,cgst:0,sgst:0,cess:0});
 let sales=[],saleItems=[],saleReturns=[],saleReturnItems=[],purchases=[],purchaseItems=[],purchaseReturns=[],purchaseReturnItems=[],pharmacy={};
 function local(d){const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)}
 function dateKey(v){const raw=String(v||"");if(!raw)return"";if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=new Date(raw);return Number.isNaN(d.getTime())?raw.slice(0,10):local(d)}
 function monthStart(){const d=new Date();return local(new Date(d.getFullYear(),d.getMonth(),1))}
 async function q(table){const r=await supabaseClient.from(table).select("*").eq("pharmacy_id",pid).limit(50000);if(r.error)throw r.error;return r.data||[]}
 function inPeriod(v){const d=dateKey(v),f=$("g3bFrom").value,t=$("g3bTo").value;return d&&(!f||d>=f)&&(!t||d<=t)}
 function isCancelled(row){return String(row?.invoice_status||row?.purchase_status||row?.return_status||row?.status||"").toLowerCase()==="cancelled"}
 function sameState(code){const home=String(pharmacy.gst_state_code||"");return !code||!home||String(code)===home}
 function split(gst,parent,explicit={}){const saved=n(explicit.igst)+n(explicit.cgst)+n(explicit.sgst);if(saved){const factor=gst/saved;return{igst:n(explicit.igst)*factor,cgst:n(explicit.cgst)*factor,sgst:n(explicit.sgst)*factor}}const inter=parent?.tax_type==="IGST"||!sameState(parent?.place_of_supply_code);return inter?{igst:gst,cgst:0,sgst:0}:{igst:0,cgst:Math.round(gst*50)/100,sgst:gst-Math.round(gst*50)/100}}
 function add(a,b,factor=1){for(const k of["taxable","igst","cgst","sgst","cess"])a[k]+=n(b[k])*factor;return a}
 function taxTotal(v){return n(v.igst)+n(v.cgst)+n(v.sgst)+n(v.cess)}
 function saleBase(item){const qty=n(item.quantity),rate=n(item.selling_rate||item.sale_rate),discount=n(item.discount_amount)||(qty*rate*n(item.discount_percent)/100);return Math.max(0,n(item.line_total)||(qty*rate-discount))}
 function saleTax(item,parent,denominators){const base=saleBase(item),denom=n(denominators.get(parent.id)),invoiceDiscount=n(parent.invoice_discount_amount),inclusive=Math.max(0,base-(denom?invoiceDiscount*base/denom:0)),gstRate=n(item.gst_percent||item.gst_rate),savedTaxable=n(item.taxable_amount),savedGst=n(item.gst_amount),factor=base>0?inclusive/base:1,taxable=(savedTaxable||savedGst)?savedTaxable*factor:(gstRate?inclusive/(1+gstRate/100):inclusive),gst=(savedTaxable||savedGst)?savedGst*factor:inclusive-taxable,sp=split(gst,parent);return{taxable,igst:sp.igst,cgst:sp.cgst,sgst:sp.sgst,cess:0}}
 function purchaseTax(item,parent,denominators){const gross=n(item.quantity)*n(item.purchase_rate),itemDiscount=n(item.discount_amount)||(gross*n(item.discount_percent)/100),base=n(item.taxable_amount)||Math.max(0,gross-itemDiscount),denom=n(denominators.get(parent.id)),invoiceDiscount=n(parent.invoice_discount_amount),taxable=Math.max(0,base-(denom?invoiceDiscount*base/denom:0)),gstRate=n(item.gst_percent),storedGst=n(item.gst_amount),gst=base>0&&storedGst?storedGst*(taxable/base):taxable*gstRate/100,sp=split(gst,parent,{igst:item.igst_amount,cgst:item.cgst_amount,sgst:item.sgst_amount});return{taxable,igst:sp.igst,cgst:sp.cgst,sgst:sp.sgst,cess:0,rate:gstRate}}
 function maps(){const saleMap=new Map(sales.map(x=>[x.id,x])),saleItemMap=new Map(saleItems.map(x=>[x.id,x])),purchaseMap=new Map(purchases.map(x=>[x.id,x])),purchaseItemMap=new Map(purchaseItems.map(x=>[x.id,x])),saleDenom=new Map(),purchaseDenom=new Map();saleItems.forEach(i=>saleDenom.set(i.sales_invoice_id,n(saleDenom.get(i.sales_invoice_id))+saleBase(i)));purchaseItems.forEach(i=>{const gross=n(i.quantity)*n(i.purchase_rate),base=n(i.taxable_amount)||Math.max(0,gross-(n(i.discount_amount)||gross*n(i.discount_percent)/100));purchaseDenom.set(i.purchase_invoice_id,n(purchaseDenom.get(i.purchase_invoice_id))+base)});return{saleMap,saleItemMap,purchaseMap,purchaseItemMap,saleDenom,purchaseDenom}}
 function outwardWorking(ctx){const gross=zero(),returns=zero();saleItems.forEach(i=>{const parent=ctx.saleMap.get(i.sales_invoice_id);if(parent&&!isCancelled(parent)&&inPeriod(parent.invoice_date||parent.created_at))add(gross,saleTax(i,parent,ctx.saleDenom))});const returnMap=new Map(saleReturns.filter(x=>!isCancelled(x)&&inPeriod(x.return_date||x.created_at)).map(x=>[x.id,x]));saleReturnItems.forEach(ri=>{if(!returnMap.has(ri.sales_return_id))return;const original=ctx.saleItemMap.get(ri.sales_item_id),parent=original&&ctx.saleMap.get(original.sales_invoice_id),sold=n(original?.quantity),returned=n(ri.return_quantity);if(!original||!parent||sold<=0||returned<=0)return;add(returns,saleTax(original,parent,ctx.saleDenom),Math.min(1,returned/sold))});const net=zero();add(net,gross);add(net,returns,-1);for(const k of Object.keys(net))if(Math.abs(net[k])<.005)net[k]=0;return{gross,returns,net}}
 function purchaseWorking(ctx){const gross=zero(),eligible=zero(),eligibleUnmatched=zero(),reversed=zero(),blocked=zero(),rates=new Map();purchaseItems.forEach(i=>{const parent=ctx.purchaseMap.get(i.purchase_invoice_id);if(!parent||isCancelled(parent)||!inPeriod(parent.purchase_date||parent.invoice_date||parent.created_at))return;const value=purchaseTax(i,parent,ctx.purchaseDenom),status=String(parent.itc_status||"Pending");add(gross,value);if(!rates.has(value.rate))rates.set(value.rate,{gross:zero(),returns:zero()});add(rates.get(value.rate).gross,value);const matched=parent.gstr2b_matched===true;if(status==="Eligible"&&matched)add(eligible,value);if(status==="Eligible"&&!matched)add(eligibleUnmatched,value);if(status==="Reversed"){add(eligible,value);add(reversed,value)}if(status==="Blocked")add(blocked,value)});
  const allReturns=zero(),eligibleReturns=zero(),returnMap=new Map(purchaseReturns.filter(x=>!isCancelled(x)&&inPeriod(x.return_date||x.created_at)).map(x=>[x.id,x]));purchaseReturnItems.forEach(ri=>{const ret=returnMap.get(ri.purchase_return_id),original=ctx.purchaseItemMap.get(ri.purchase_item_id),parent=original&&ctx.purchaseMap.get(original.purchase_invoice_id);if(!ret||!original||!parent)return;let value;if(n(ri.taxable_amount)||n(ri.gst_amount)){const gst=n(ri.gst_amount),sp=split(gst,ret,{igst:ri.igst_amount,cgst:ri.cgst_amount,sgst:ri.sgst_amount});value={taxable:n(ri.taxable_amount),igst:sp.igst,cgst:sp.cgst,sgst:sp.sgst,cess:0,rate:n(ri.gst_percent)}}else{const originalValue=purchaseTax(original,parent,ctx.purchaseDenom),paidReturned=n(ri.paid_return_quantity||ri.return_quantity),ratio=n(original.quantity)>0?Math.min(1,paidReturned/n(original.quantity)):0;value={...zero(),rate:originalValue.rate};add(value,originalValue,ratio)}add(allReturns,value);if(String(parent.itc_status||"Pending")==="Eligible"&&parent.gstr2b_matched===true)add(eligibleReturns,value);if(!rates.has(value.rate))rates.set(value.rate,{gross:zero(),returns:zero()});add(rates.get(value.rate).returns,value)});return{gross,eligible,eligibleUnmatched,reversed,blocked,allReturns,eligibleReturns,rates}}
 function tr(label,v,withTaxable=true){return`<tr><td>${UI.safe(label)}</td>${withTaxable?`<td>${m(v.taxable)}</td>`:""}<td>${m(v.igst)}</td><td>${m(v.cgst)}</td><td>${m(v.sgst)}</td><td>${m(v.cess)}</td></tr>`}
 function render(){const ctx=maps(),ow=outwardWorking(ctx),pw=purchaseWorking(ctx),reversals=zero(),netItc=zero();add(reversals,pw.reversed);add(reversals,pw.eligibleReturns);add(netItc,pw.eligible);add(netItc,reversals,-1);const output=taxTotal(ow.net),reviewed=taxTotal(pw.eligible),reversalTotal=taxTotal(reversals),netInput=taxTotal(netItc);$("g3bOutTaxable").textContent=m(ow.net.taxable);$("g3bOutput").textContent=m(output);$("g3bInput").textContent=m(reviewed);$("g3bReversal").textContent=m(reversalTotal);$("g3bNetInput").textContent=m(netInput);$("g3bDifference").textContent=m(output-netInput);$("g3bOutwardNote").textContent=`Gross outward GST ${m(taxTotal(ow.gross))} − sales-return GST ${m(taxTotal(ow.returns))} = net output GST ${m(output)}.`;$("g3bItcNote").textContent=`2B-matched eligible ITC ${m(reviewed)}. Eligible but not GSTR-2B matched and therefore excluded: ${m(taxTotal(pw.eligibleUnmatched))}.`;
  $("g3b31").innerHTML=[tr("3.1(a) Net outward taxable supplies after sales returns",ow.net),tr("3.1(b) Outward taxable supplies (zero rated)",zero()),tr("3.1(c) Other outward supplies (nil rated, exempted)",zero()),tr("3.1(d) Inward supplies liable to reverse charge",zero()),tr("3.1(e) Non-GST outward supplies",zero())].join("");
  $("g3b4").innerHTML=[tr("4(A)(1) Import of goods",zero(),false),tr("4(A)(2) Import of services",zero(),false),tr("4(A)(3) Inward supplies liable to reverse charge",zero(),false),tr("4(A)(4) Inward supplies from ISD",zero(),false),tr("4(A)(5) GSTR-2B matched eligible ITC before reversals",pw.eligible,false),tr("4(B)(1) Reversal — Rules 38/42/43 and Section 17(5)",zero(),false),tr("4(B)(2) Other reversals — manual and eligible purchase returns",reversals,false),tr("4(C) Net ITC Available — working",netItc,false),tr("4(D)(1) ITC reclaimed from earlier-period reversals",zero(),false),tr("4(D)(2) Ineligible / Blocked ITC",pw.blocked,false)].join("");
  $("g3bPurchaseRates").innerHTML=[...pw.rates.entries()].sort((a,b)=>a[0]-b[0]).map(([rate,v])=>{const net=zero();add(net,v.gross);add(net,v.returns,-1);return`<tr><td>${rate}%</td><td>${m(v.gross.taxable)}</td><td>${m(taxTotal(v.gross))}</td><td>${m(v.returns.taxable)}</td><td>${m(taxTotal(v.returns))}</td><td>${m(net.taxable)}</td><td>${m(taxTotal(net))}</td></tr>`}).join("")||'<tr><td colspan="7">No purchases in selected period.</td></tr>'}
 async function load(){[sales,saleItems,saleReturns,saleReturnItems,purchases,purchaseItems,purchaseReturns,purchaseReturnItems]=await Promise.all([q("sales_invoices"),q("sales_items"),q("sales_returns"),q("sales_return_items"),q("purchase_invoices"),q("purchase_items"),q("purchase_returns"),q("purchase_return_items")]);const{data,error}=await supabaseClient.from("pharmacies").select("id,gst_state_code,registered_state,state").eq("id",pid).maybeSingle();if(error)throw error;pharmacy=data||{};render()}
 function csv(){const tables=[...document.querySelectorAll(".g3b table")],lines=[];tables.forEach(t=>{lines.push([...t.querySelectorAll("thead th")].map(x=>`"${x.textContent}"`).join(","));[...t.querySelectorAll("tbody tr")].forEach(r=>lines.push([...r.children].map(x=>`"${x.textContent.replaceAll('"','""')}"`).join(",")));lines.push("")});const a=document.createElement("a"),u=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv"}));a.href=u;a.download=`Medvika_GSTR3B_Working_${$("g3bFrom").value}_to_${$("g3bTo").value}.csv`;a.click();URL.revokeObjectURL(u)}
 $("g3bFrom").value=monthStart();$("g3bTo").value=local(new Date());$("g3bFrom").onchange=render;$("g3bTo").onchange=render;$("g3bRefresh").onclick=load;$("g3bPrint").onclick=()=>window.print();$("g3bCsv").onclick=csv;try{await load()}catch(e){UI.toast("GSTR-3B working report could not load: "+e.message,"error")}
};
