window.initInputGstModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id,n=v=>Number.isFinite(Number(v))?Number(v):0,m=v=>UI.money(n(v));
 let invoices=[],items=[],suppliers=[],pharmacy={},rows=[],editing=null,validated=null,importHistory=[],reconciliationDocuments=[],reviewDocumentId=null;
 const alias=(value)=>String(value??"").toLowerCase().replace(/[^a-z0-9]/g,"");
 const val=(row,names)=>{const map=row.__normalized||Object.fromEntries(Object.entries(row).map(([k,v])=>[alias(k),v]));row.__normalized=map;for(const name of names){const found=map[alias(name)];if(found!==undefined&&found!==null&&String(found).trim()!=="")return found;}return null};
 const amount=value=>{const x=Number(String(value??"").replace(/[₹,\s]/g,"").replace(/^\((.*)\)$/,"-$1"));return Number.isFinite(x)?Math.abs(x):0};
 const gstin=value=>String(value||"").toUpperCase().replace(/\s/g,"");
 const docNo=value=>String(value||"").trim();
 const normalizedDoc=value=>docNo(value).toUpperCase().replace(/[^A-Z0-9]/g,"");
 function local(d){const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)}
 function dateKey(v){const raw=String(v||"");if(!raw)return"";if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=new Date(raw);return Number.isNaN(d.getTime())?raw.slice(0,10):local(d)}
 function monthStart(){const d=new Date();return local(new Date(d.getFullYear(),d.getMonth(),1))}
 function inPeriod(d){d=dateKey(d);return d&&(!$("itcFrom").value||d>=$("itcFrom").value)&&(!$("itcTo").value||d<=$("itcTo").value)}
 function gstCode(g){g=String(g||"").trim().toUpperCase();return /^\d{2}[A-Z0-9]{13}$/.test(g)?g.slice(0,2):""}
 function split(gst,invoice,supplier){if(invoice?.tax_type==="IGST")return{igst:gst,cgst:0,sgst:0};if(invoice?.tax_type==="CGST_SGST")return{igst:0,cgst:Math.round(gst*50)/100,sgst:gst-Math.round(gst*50)/100};const home=String(pharmacy.gst_state_code||gstCode(pharmacy.gst_number)),other=String(supplier?.state_code||gstCode(supplier?.gstin||supplier?.gst_number));if(home&&other)return home!==other?{igst:gst,cgst:0,sgst:0}:{igst:0,cgst:Math.round(gst*50)/100,sgst:gst-Math.round(gst*50)/100};return{igst:0,cgst:0,sgst:0}}
 function parseDate(value){
  if(value===null||value===undefined||value==="")return"";
  if(typeof value==="number"&&window.XLSX?.SSF){const d=XLSX.SSF.parse_date_code(value);if(d)return`${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`}
  const s=String(value).trim(),iso=s.match(/^(\d{4})[-\/]([01]?\d)[-\/]([0-3]?\d)/);if(iso)return`${iso[1]}-${iso[2].padStart(2,"0")}-${iso[3].padStart(2,"0")}`;
  const ind=s.match(/^([0-3]?\d)[-\/]([01]?\d)[-\/](\d{2}|\d{4})$/);if(ind){let y=ind[3];if(y.length===2)y=`20${y}`;return`${y}-${ind[2].padStart(2,"0")}-${ind[1].padStart(2,"0")}`}
  const d=new Date(s);return Number.isNaN(d.getTime())?"":local(d);
 }
 function normalizeRow(row,meta={}){
  const supplierGstin=gstin(val(row,["GSTIN of supplier","Supplier GSTIN","GSTIN","ctin"]));
  const number=docNo(val(row,["Invoice number","Invoice No","Document number","Note number","nt_num","inum"]));
  const date=parseDate(val(row,["Invoice Date","Document Date","Note date","nt_dt","idt"]));
  const documentType=String(val(row,["Document type","Invoice type","Note type"])||meta.documentType||"INVOICE").toUpperCase();
  return{
   source_row_number:meta.rowNumber,source_section:meta.section||null,document_type:documentType,
   supplier_gstin:supplierGstin,supplier_name:String(val(row,["Trade/Legal name","Trade Name","Legal Name","Supplier Name","trdnm"] )||meta.supplierName||"").trim()||null,
   document_number:number,document_date:date,place_of_supply_code:String(val(row,["Place of Supply","Place of supply code","pos"])||"").match(/\d{2}/)?.[0]||null,
   reverse_charge:/^(y|yes|true|1)$/i.test(String(val(row,["Reverse Charge","Reverse charge applicable","rchrg"])||"")),
   taxable_value:amount(val(row,["Taxable Value","Taxable Value (₹)","txval"])),igst_amount:amount(val(row,["Integrated Tax","IGST","iamt"])),
   cgst_amount:amount(val(row,["Central Tax","CGST","camt"])),sgst_amount:amount(val(row,["State/UT Tax","State Tax","SGST","samt"])),cess_amount:amount(val(row,["Cess","csamt"])),
   itc_availability:String(val(row,["ITC Availability","ITC available","itcavl"])||"").trim()||null,itc_reason:String(val(row,["Reason","ITC Reason","rsn"])||"").trim()||null,
   filing_status:String(val(row,["Filing Status","filing_status"])||"").trim()||null,filing_date:parseDate(val(row,["Filing Date","filing_date"]))||null,
   normalized_supplier_gstin:supplierGstin,normalized_document_number:normalizedDoc(number),raw_payload:meta.raw||Object.fromEntries(Object.entries(row).filter(([k])=>k!=="__normalized"))
  };
 }
 function validateDocument(doc){const errors=[];if(!/^\d{2}[A-Z0-9]{13}$/.test(doc.supplier_gstin))errors.push("invalid supplier GSTIN");if(!doc.document_number)errors.push("missing document number");if(!doc.document_date)errors.push("invalid document date");if(!doc.taxable_value&&!doc.igst_amount&&!doc.cgst_amount&&!doc.sgst_amount&&!doc.cess_amount)errors.push("no taxable/tax values");return errors}
 function excelDocuments(buffer){
  const wb=XLSX.read(buffer,{type:"array",cellDates:false}),documents=[],invalid=[];let serial=0;
  wb.SheetNames.forEach(sheetName=>{const matrix=XLSX.utils.sheet_to_json(wb.Sheets[sheetName],{header:1,defval:"",raw:true});let headerIndex=-1;
   for(let i=0;i<Math.min(matrix.length,35);i++){const h=matrix[i].map(alias);if(h.some(x=>x.includes("gstinofsupplier")||x==="suppliergstin"||x==="gstin")&&h.some(x=>x.includes("invoicenumber")||x.includes("documentnumber")||x.includes("notenumber"))){headerIndex=i;break}}
   if(headerIndex<0)return;const headers=matrix[headerIndex].map(x=>String(x||"").trim());
   matrix.slice(headerIndex+1).forEach((cells,index)=>{const row={};headers.forEach((h,j)=>{if(h)row[h]=cells[j]});if(!cells.some(x=>String(x??"").trim()))return;serial++;const doc=normalizeRow(row,{rowNumber:serial,section:sheetName,documentType:/cdn|credit|debit/i.test(sheetName)?"CREDIT_DEBIT_NOTE":"INVOICE"});const errors=validateDocument(doc);if(errors.length)invalid.push({sheet:sheetName,row:headerIndex+index+2,errors});else documents.push(doc)});
  });return{documents,invalid};
 }
 function taxTotals(node){const out={taxable_value:0,igst_amount:0,cgst_amount:0,sgst_amount:0,cess_amount:0};(function walk(v){if(Array.isArray(v)){v.forEach(walk);return}if(!v||typeof v!=="object")return;const hasTax=["txval","iamt","camt","samt","csamt"].some(k=>v[k]!==undefined);if(hasTax){out.taxable_value+=amount(v.txval);out.igst_amount+=amount(v.iamt);out.cgst_amount+=amount(v.camt);out.sgst_amount+=amount(v.samt);out.cess_amount+=amount(v.csamt);return}Object.values(v).forEach(walk)})(node);return out}
 function jsonDocuments(data){const documents=[],invalid=[];let serial=0;
  (function walk(node,ctx={},path=[]){if(Array.isArray(node)){node.forEach(x=>walk(x,ctx,path));return}if(!node||typeof node!=="object")return;const next={...ctx};if(node.ctin||node.gstin)next.gstin=node.ctin||node.gstin;if(node.trdnm||node.supplier_name)next.supplierName=node.trdnm||node.supplier_name;
   const key=String(path[path.length-1]||"");if(/^(b2b|b2ba|cdnr|cdnra|isd|impg|impgsez)$/i.test(key))next.section=key.toUpperCase();
   const number=node.inum||node.nt_num||node.document_number||node.invoice_number,date=node.idt||node.nt_dt||node.document_date||node.invoice_date;
   if(number&&date){serial++;const totals=taxTotals(node.itms||node.items||node);const row={...node,"GSTIN of supplier":next.gstin,"Trade/Legal name":next.supplierName,"Document number":number,"Document Date":date,"Taxable Value":totals.taxable_value,"Integrated Tax":totals.igst_amount,"Central Tax":totals.cgst_amount,"State/UT Tax":totals.sgst_amount,"Cess":totals.cess_amount};const doc=normalizeRow(row,{rowNumber:serial,section:next.section||path.join("."),documentType:/cdn|note/i.test(next.section||"")?"CREDIT_DEBIT_NOTE":"INVOICE",supplierName:next.supplierName,raw:node});const errors=validateDocument(doc);if(errors.length)invalid.push({path:path.join("."),document:number,errors});else documents.push(doc);return}
   Object.entries(node).forEach(([k,v])=>walk(v,next,[...path,k]));
  })(data);return{documents,invalid};
 }
 async function fileHash(file){const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
 async function validateFile(){
  const file=$("gstr2bFile").files?.[0],period=$("gstr2bPeriod").value;validated=null;$("gstr2bImport").disabled=true;
  if(!period)return UI.toast("Select the GSTR-2B return period.","warning");if(!file)return UI.toast("Choose a GST portal Excel or JSON file.","warning");
  try{$("gstr2bValidate").disabled=true;let parsed,format;if(/\.json$/i.test(file.name)){format="JSON";parsed=jsonDocuments(JSON.parse(await file.text()))}else if(/\.xlsx?$/i.test(file.name)){if(!window.XLSX)throw new Error("Excel reader is not available.");format="EXCEL";parsed=excelDocuments(await file.arrayBuffer())}else throw new Error("Use a .xlsx, .xls or .json file.");
   if(!parsed.documents.length)throw new Error("No valid supplier invoice rows were detected in this file.");validated={...parsed,file,format,period:`${period}-01`,hash:await fileHash(file)};renderPreview();$("gstr2bImport").disabled=parsed.invalid.length>0;
  }catch(e){UI.toast("GSTR-2B validation failed: "+e.message,"error")}finally{$("gstr2bValidate").disabled=false}
 }
 function renderPreview(){const docs=validated.documents,invalid=validated.invalid,taxable=docs.reduce((s,x)=>s+x.taxable_value,0),tax=docs.reduce((s,x)=>s+x.igst_amount+x.cgst_amount+x.sgst_amount+x.cess_amount,0);$("gstr2bPreview").hidden=false;$("gstr2bValidCount").textContent=docs.length;$("gstr2bInvalidCount").textContent=invalid.length;$("gstr2bTaxable").textContent=m(taxable);$("gstr2bTax").textContent=m(tax);const msg=$("gstr2bValidationMessage");msg.classList.toggle("error",invalid.length>0);msg.textContent=invalid.length?`${invalid.length} row(s) have missing/invalid GSTIN, document number, date or tax values. Correct the source file before import.`:"Validation passed. Review the preview and import the statement.";$("gstr2bPreviewBody").innerHTML=docs.slice(0,20).map(x=>`<tr><td>${UI.safe(x.supplier_gstin)}</td><td>${UI.safe(x.supplier_name||"—")}</td><td>${UI.safe(x.document_number)}</td><td>${UI.safe(x.document_date)}</td><td>${m(x.taxable_value)}</td><td>${m(x.igst_amount)}</td><td>${m(x.cgst_amount)}</td><td>${m(x.sgst_amount)}</td><td>${m(x.cess_amount)}</td></tr>`).join("")+(docs.length>20?`<tr><td colspan="9" class="empty">Previewing 20 of ${docs.length} documents.</td></tr>`:"")}
 async function importStatement(){
  if(!validated||validated.invalid.length)return;const button=$("gstr2bImport");button.disabled=true;button.textContent="Importing...";let importId=null;
  try{const docs=validated.documents,taxable=docs.reduce((s,x)=>s+x.taxable_value,0),igst=docs.reduce((s,x)=>s+x.igst_amount,0),cgst=docs.reduce((s,x)=>s+x.cgst_amount,0),sgst=docs.reduce((s,x)=>s+x.sgst_amount,0),cess=docs.reduce((s,x)=>s+x.cess_amount,0);
   const header={pharmacy_id:pid,return_period:validated.period,source_format:validated.format,source_filename:validated.file.name,source_hash:validated.hash,status:"IMPORTING",record_count:docs.length,taxable_value:taxable,igst_amount:igst,cgst_amount:cgst,sgst_amount:sgst,cess_amount:cess};
   const created=await supabaseClient.from("gstr2b_imports").insert(header).select("id").single();if(created.error){if(created.error.code==="23505")throw new Error("This file has already been imported for the selected period.");throw created.error}importId=created.data.id;
   for(let i=0;i<docs.length;i+=250){const batch=docs.slice(i,i+250).map(x=>({...x,import_id:importId,pharmacy_id:pid,return_period:validated.period}));const inserted=await supabaseClient.from("gstr2b_documents").insert(batch);if(inserted.error)throw inserted.error}
   const matched=await supabaseClient.rpc("match_gstr2b_import",{p_import_id:importId});if(matched.error)throw matched.error;
   const counts=matched.data||{},matchedCount=n(counts.MATCHED),reviewCount=n(counts.VALUE_MISMATCH)+n(counts.DATE_MISMATCH)+n(counts.GSTIN_MISMATCH)+n(counts.MULTIPLE_CANDIDATES),unmatchedCount=n(counts.UNMATCHED);
   UI.toast(`GSTR-2B imported: ${docs.length} documents; ${matchedCount} matched, ${reviewCount} need review, ${unmatchedCount} unmatched.`);validated=null;$("gstr2bFile").value="";$("gstr2bPreview").hidden=true;await loadImports();
  }catch(e){if(importId){await supabaseClient.from("gstr2b_documents").delete().eq("import_id",importId).eq("pharmacy_id",pid);await supabaseClient.from("gstr2b_imports").update({status:"FAILED",error_message:String(e.message).slice(0,500)}).eq("id",importId).eq("pharmacy_id",pid)}UI.toast("GSTR-2B import failed: "+e.message,"error")}finally{button.textContent="Import Validated Statement";button.disabled=!validated||validated.invalid.length>0}
 }
 async function rerunMatching(importId,button){try{button.disabled=true;button.textContent="Matching...";const r=await supabaseClient.rpc("match_gstr2b_import",{p_import_id:importId});if(r.error)throw r.error;const c=r.data||{},matched=n(c.MATCHED),review=n(c.VALUE_MISMATCH)+n(c.DATE_MISMATCH)+n(c.GSTIN_MISMATCH)+n(c.MULTIPLE_CANDIDATES),unmatched=n(c.UNMATCHED);UI.toast(`Matching complete: ${matched} matched, ${review} need review, ${unmatched} unmatched.`);await Promise.all([load(),loadImports(),loadReconciliation()])}catch(e){UI.toast("GSTR-2B matching failed: "+e.message,"error")}finally{if(button?.isConnected){button.disabled=false;button.textContent="Re-run Matching"}}}
 async function loadImports(){const r=await supabaseClient.from("gstr2b_imports").select("*").eq("pharmacy_id",pid).order("imported_at",{ascending:false}).limit(24);if(r.error)throw r.error;importHistory=r.data||[];$("gstr2bImportCount").textContent=`${importHistory.length} import${importHistory.length===1?"":"s"}`;$("gstr2bImportBody").innerHTML=importHistory.map(x=>{const tax=n(x.igst_amount)+n(x.cgst_amount)+n(x.sgst_amount)+n(x.cess_amount);return`<tr><td>${UI.safe(String(x.return_period).slice(0,7))}</td><td>${UI.safe(x.source_filename)}</td><td>${UI.safe(x.source_format)}</td><td>${n(x.record_count)}</td><td>${m(x.taxable_value)}</td><td>${m(tax)}</td><td class="status-${String(x.status).toLowerCase()}">${UI.safe(String(x.status).replaceAll("_"," "))}</td><td>${UI.safe(new Date(x.imported_at).toLocaleString("en-IN"))}</td><td><button class="rerun-2b" data-id="${x.id}">Re-run Matching</button></td></tr>`}).join("")||'<tr><td colspan="9" class="empty">No GSTR-2B files imported.</td></tr>';document.querySelectorAll(".rerun-2b").forEach(b=>b.onclick=()=>rerunMatching(b.dataset.id,b))}

 function invoiceLabel(invoice){if(!invoice)return"—";const supplier=suppliers.find(x=>x.id===invoice.supplier_id)||{};return `${invoice.purchase_number||invoice.invoice_number||"Purchase"} / ${invoice.supplier_invoice_number||"No supplier invoice"} / ${supplier.name||"Supplier"}`}
 function reconciliationList(){const filter=$("gstr2bMatchFilter").value,period=$("gstr2bReconPeriod").value;return reconciliationDocuments.filter(x=>(!period||String(x.return_period).slice(0,7)===period)&&(!filter||x.match_status===filter))}
 function renderReconciliation(){const list=reconciliationList(),matched=reconciliationDocuments.filter(x=>["MATCHED","MANUAL_MATCH"].includes(x.match_status)).length,review=reconciliationDocuments.filter(x=>["VALUE_MISMATCH","DATE_MISMATCH","GSTIN_MISMATCH","MULTIPLE_CANDIDATES"].includes(x.match_status)).length,unmatched=reconciliationDocuments.filter(x=>x.match_status==="UNMATCHED").length;$("gstr2bMatchedCount").textContent=matched;$("gstr2bReviewCount").textContent=review;$("gstr2bUnmatchedCount").textContent=unmatched;$("gstr2bReconCount").textContent=`${list.length} documents`;$("gstr2bReconBody").innerHTML=list.map(x=>{const inv=invoices.find(i=>i.id===x.matched_purchase_invoice_id),tax=n(x.igst_amount)+n(x.cgst_amount)+n(x.sgst_amount)+n(x.cess_amount);return `<tr><td>${UI.safe(String(x.return_period).slice(0,7))}</td><td>${UI.safe(x.supplier_gstin)}</td><td>${UI.safe(x.document_number)}</td><td>${UI.safe(x.document_date)}</td><td>${m(x.taxable_value)}</td><td>${m(tax)}</td><td class="match-${String(x.match_status).toLowerCase()}">${UI.safe(x.match_status)}</td><td>${UI.safe(invoiceLabel(inv))}</td><td>${UI.safe(x.review_notes||"—")}</td><td><button class="review-2b" data-id="${x.id}">Review</button></td></tr>`}).join("")||'<tr><td colspan="10" class="empty">No reconciliation documents for this filter.</td></tr>';document.querySelectorAll(".review-2b").forEach(b=>b.onclick=()=>openGstr2bReview(b.dataset.id))}
 function exportReconciliationCsv(){const list=reconciliationList();if(!list.length)return UI.toast("No reconciliation rows to export.","warning");const heads=["Return Period","Supplier GSTIN","Supplier","Portal Document","Document Date","Taxable Value","IGST","CGST","SGST","Cess","Match Status","ERP Purchase","Confidence","Review Notes"],data=list.map(x=>{const inv=invoices.find(i=>i.id===x.matched_purchase_invoice_id);return[String(x.return_period).slice(0,7),x.supplier_gstin,x.supplier_name||"",x.document_number,x.document_date,x.taxable_value,x.igst_amount,x.cgst_amount,x.sgst_amount,x.cess_amount,x.match_status,invoiceLabel(inv),x.match_confidence??"",x.review_notes||""]}),esc=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[heads,...data].map(r=>r.map(esc).join(",")).join("\n"),a=document.createElement("a"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.href=u;a.download=`Medvika_GSTR2B_Reconciliation_${$("gstr2bReconPeriod").value||"all-periods"}_${$("gstr2bMatchFilter").value||"all-statuses"}.csv`;a.click();URL.revokeObjectURL(u)}
 async function loadReconciliation(){const r=await supabaseClient.from("gstr2b_documents").select("*").eq("pharmacy_id",pid).order("return_period",{ascending:false}).order("source_row_number",{ascending:true}).limit(5000);if(r.error)throw r.error;reconciliationDocuments=r.data||[];renderReconciliation()}
 function openGstr2bReview(id){const doc=reconciliationDocuments.find(x=>x.id===id);if(!doc)return;reviewDocumentId=id;$("gstr2bReviewLabel").textContent=`${doc.supplier_gstin} / ${doc.document_number} / ${doc.document_date} / ${doc.match_status}`;$("gstr2bPurchaseCandidate").innerHTML='<option value="">Select ERP purchase invoice</option>'+invoices.filter(x=>String(x.purchase_status||x.invoice_status||"").toLowerCase()!=="cancelled").map(x=>`<option value="${x.id}">${UI.safe(invoiceLabel(x))}</option>`).join("");$("gstr2bPurchaseCandidate").value=doc.matched_purchase_invoice_id||"";$("gstr2bReviewNotes").value=doc.review_notes||"";$("gstr2bReviewModal").hidden=false}
 async function clearOldMatch(oldId,newId){if(!oldId||oldId===newId)return;const r=await supabaseClient.from("gstr2b_documents").select("id",{count:"exact",head:true}).eq("pharmacy_id",pid).eq("matched_purchase_invoice_id",oldId).in("match_status",["MATCHED","MANUAL_MATCH"]);if(!r.error&&!r.count)await supabaseClient.from("purchase_invoices").update({gstr2b_matched:false,itc_status:"Pending"}).eq("id",oldId).eq("pharmacy_id",pid)}
 async function saveGstr2bReview(action){const doc=reconciliationDocuments.find(x=>x.id===reviewDocumentId);if(!doc)return;const purchaseId=$("gstr2bPurchaseCandidate").value||null,notes=$("gstr2bReviewNotes").value.trim();if(action==="MANUAL_MATCH"&&!purchaseId)return UI.toast("Select the matching ERP purchase invoice.","warning");if(action==="IGNORED"&&!notes)return UI.toast("Enter a reason for ignoring this portal row.","warning");const user=await supabaseClient.auth.getUser(),userId=user.data?.user?.id||null,payload=action==="MANUAL_MATCH"?{matched_purchase_invoice_id:purchaseId,match_status:"MANUAL_MATCH",match_confidence:100,matched_by:userId,matched_at:new Date().toISOString(),review_notes:notes||"Manually verified"}:{matched_purchase_invoice_id:null,match_status:"IGNORED",match_confidence:0,matched_by:userId,matched_at:new Date().toISOString(),review_notes:notes};const u=await supabaseClient.from("gstr2b_documents").update(payload).eq("id",doc.id).eq("pharmacy_id",pid);if(u.error)return UI.toast(u.error.message,"error");if(action==="MANUAL_MATCH"){const p=await supabaseClient.from("purchase_invoices").update({gstr2b_matched:true}).eq("id",purchaseId).eq("pharmacy_id",pid);if(p.error)return UI.toast(p.error.message,"error")}await clearOldMatch(doc.matched_purchase_invoice_id,purchaseId);$("gstr2bReviewModal").hidden=true;UI.toast(action==="MANUAL_MATCH"?"Manual match approved.":"Portal row ignored.");await Promise.all([load(),loadReconciliation(),loadImports()])}
 function build(){const sm=new Map(suppliers.map(x=>[x.id,x])),groups=new Map();invoices.filter(x=>inPeriod(x.purchase_date||x.created_at)&&String(x.purchase_status||x.status||"").toLowerCase()!=="cancelled").forEach(x=>groups.set(x.id,{invoice:x,supplier:sm.get(x.supplier_id)||{},taxable:0,gst:0,igst:0,cgst:0,sgst:0}));items.forEach(i=>{const g=groups.get(i.purchase_invoice_id||i.purchase_id);if(!g)return;const gross=n(i.quantity)*n(i.purchase_rate),disc=gross*n(i.discount_percent)/100,taxable=gross-disc,gst=n(i.gst_amount)||(taxable*n(i.gst_percent)/100),saved=n(i.igst_amount)+n(i.cgst_amount)+n(i.sgst_amount),sp=saved?{igst:n(i.igst_amount),cgst:n(i.cgst_amount),sgst:n(i.sgst_amount)}:split(gst,g.invoice,g.supplier);g.taxable+=n(i.taxable_amount)||taxable;g.gst+=gst;g.igst+=sp.igst;g.cgst+=sp.cgst;g.sgst+=sp.sgst});rows=[...groups.values()]}
 function render(){const sf=$("itcStatusFilter").value,list=rows.filter(x=>!sf||String(x.invoice.itc_status||"Pending")===sf);let taxable=0,gross=0,eligible=0,pending=0,restricted=0;rows.forEach(x=>{taxable+=x.taxable;gross+=x.gst;const s=x.invoice.itc_status||"Pending";if(s==="Eligible"&&x.invoice.gstr2b_matched===true)eligible+=x.gst;else if(s==="Pending"||(s==="Eligible"&&x.invoice.gstr2b_matched!==true))pending+=x.gst;else restricted+=x.gst});$("itcTaxable").textContent=m(taxable);$("itcGross").textContent=m(gross);$("itcEligible").textContent=m(eligible);$("itcPending").textContent=m(pending);$("itcRestricted").textContent=m(restricted);$("itcCount").textContent=`${list.length} invoices`;$("itcBody").innerHTML=list.map(x=>{const i=x.invoice,s=x.supplier,status=i.itc_status||"Pending",supplierGstin=s.gstin||s.gst_number||"—",pos=[s.state,s.state_code?`(${s.state_code})`:""].filter(Boolean).join(" ")||"—";return`<tr><td>${UI.safe(i.purchase_number||"—")}</td><td>${UI.safe(i.supplier_invoice_number||"—")}</td><td>${UI.safe(dateKey(i.purchase_date||i.invoice_date||i.created_at))}</td><td>${UI.safe(s.supplier_name||s.name||s.company_name||s.trade_name||"Supplier")}</td><td>${UI.safe(supplierGstin)}</td><td>${UI.safe(pos)}</td><td>${m(x.taxable)}</td><td>${m(x.igst)}</td><td>${m(x.cgst)}</td><td>${m(x.sgst)}</td><td><b>${m(x.gst)}</b></td><td><span class="badge">${UI.safe(status)}</span></td><td>${i.gstr2b_matched?"Matched":"Not matched"}</td><td><button class="review" data-id="${i.id}">Review</button></td></tr>`}).join("")||'<tr><td colspan="14" class="empty">No purchases in this period.</td></tr>';document.querySelectorAll(".review").forEach(b=>b.onclick=()=>openReview(b.dataset.id))}
 function openReview(id){const x=rows.find(r=>r.invoice.id===id);if(!x)return;editing=id;$("itcInvoiceLabel").textContent=`${x.invoice.purchase_number||""} / Supplier Invoice ${x.invoice.supplier_invoice_number||""}`;$("itcEditStatus").value=x.invoice.itc_status||"Pending";$("itc2bMatched").checked=!!x.invoice.gstr2b_matched;$("itcReason").value=x.invoice.itc_review_notes||"";$("itcModal").hidden=false}
 async function saveReview(){const status=$("itcEditStatus").value,notes=$("itcReason").value.trim(),current=rows.find(x=>x.invoice.id===editing)?.invoice;if(status==="Eligible"&&current?.gstr2b_matched!==true)return UI.toast("Reconcile and match this invoice with GSTR-2B before marking ITC Eligible.","warning");if(["Reversed","Blocked"].includes(status)&&!notes)return UI.toast("Enter a reason for Reversed / Blocked ITC.","warning");const{error}=await supabaseClient.from("purchase_invoices").update({itc_status:status,itc_review_notes:notes||null,itc_reviewed_at:new Date().toISOString()}).eq("id",editing).eq("pharmacy_id",pid);if(error)return UI.toast(error.message,"error");$("itcModal").hidden=true;UI.toast("ITC review saved.");await load()}
 async function load(){const [a,b,c,p]=await Promise.all([supabaseClient.from("purchase_invoices").select("*").eq("pharmacy_id",pid).limit(50000),supabaseClient.from("purchase_items").select("*").limit(50000),supabaseClient.from("suppliers").select("*").eq("pharmacy_id",pid).limit(50000),supabaseClient.from("pharmacies").select("gst_number,gst_state_code").eq("id",pid).maybeSingle()]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;invoices=a.data||[];items=b.data||[];suppliers=c.data||[];pharmacy=p.data||{};build();render()}
 function csv(){const heads=[...document.querySelectorAll(".itc-module table thead th")].slice(-14,-1).map(x=>x.textContent),data=[...document.querySelectorAll("#itcBody tr")].filter(r=>r.children.length>1).map(r=>[...r.children].slice(0,-1).map(x=>x.textContent.trim())),esc=v=>`"${String(v).replaceAll('"','""')}"`,text=[heads,...data].map(r=>r.map(esc).join(",")).join("\n"),a=document.createElement("a"),u=URL.createObjectURL(new Blob([text],{type:"text/csv"}));a.href=u;a.download=`Medvika_Input_GST_ITC_${$("itcFrom").value}_to_${$("itcTo").value}.csv`;a.click();URL.revokeObjectURL(u)}
 $("gstr2bPeriod").value=monthStart().slice(0,7);$("gstr2bReconPeriod").value=monthStart().slice(0,7);$("gstr2bReconPeriod").onchange=renderReconciliation;$("gstr2bMatchFilter").onchange=renderReconciliation;$("gstr2bReconCsv").onclick=exportReconciliationCsv;$("gstr2bReviewClose").onclick=()=>{$("gstr2bReviewModal").hidden=true};$("gstr2bApprove").onclick=()=>saveGstr2bReview("MANUAL_MATCH");$("gstr2bIgnore").onclick=()=>saveGstr2bReview("IGNORED");$("gstr2bValidate").onclick=validateFile;$("gstr2bImport").onclick=importStatement;$("gstr2bFile").onchange=()=>{validated=null;$("gstr2bImport").disabled=true;$("gstr2bPreview").hidden=true};$("itcFrom").value=monthStart();$("itcTo").value=local(new Date());$("itcFrom").onchange=render;$("itcTo").onchange=render;$("itcStatusFilter").onchange=render;$("itcRefresh").onclick=async()=>{await Promise.all([load(),loadImports(),loadReconciliation()])};$("itcPrint").onclick=()=>window.print();$("itcCsv").onclick=csv;$("itcClose").onclick=()=>{$("itcModal").hidden=true};$("itcSave").onclick=saveReview;
 try{await load();await Promise.all([loadImports(),loadReconciliation()])}catch(e){UI.toast("Input GST register could not load: "+e.message,"error")}
};
