window.initPurchaseReportModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id;
 const n=v=>Number.isFinite(Number(v))?Number(v):0,m=v=>UI.money(n(v)),s=v=>UI.safe(v??"");let rows=[],returns=[],visible=[];if(!pid){UI.toast("Pharmacy profile not available.","error");return;}
 const P="pr",E=x=>$(P+x),first=(o,ks,d="")=>{for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null&&o[k]!=="")return o[k];return d;};
 const dateKey=value=>{const raw=String(value||"");if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=new Date(raw);if(Number.isNaN(d.getTime()))return raw.slice(0,10);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-");};
 function dates(){const d=new Date(),f=new Date(d.getFullYear(),d.getMonth(),1),L=x=>new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10);E("From").value=L(f);E("To").value=L(d);}
 async function load(){const [purchaseResult,returnResult]=await Promise.all([supabaseClient.from("purchase_invoices").select("*,suppliers(name)").eq("pharmacy_id",pid).order("purchase_date",{ascending:false}).limit(30000),supabaseClient.from("purchase_returns").select("id,purchase_invoice_id,return_date,return_amount,supplier_total_credit,return_status").eq("pharmacy_id",pid).limit(30000)]);if(purchaseResult.error)throw purchaseResult.error;if(returnResult.error)throw returnResult.error;rows=purchaseResult.data||[];returns=returnResult.data||[];apply();}
 let reportInvoiceMarkup="";
 function invoiceMarkup(invoice,lines){const date=v=>v?new Date(v).toLocaleDateString("en-IN"):"—",supplier=invoice.suppliers||{};return `<article class="purchase-invoice-document"><header><div><h2>PURCHASE INVOICE</h2><b>${s(invoice.purchase_number||"—")}</b></div><div><b>${s(supplier.name||"Supplier")}</b><br>${s(invoice.supplier_invoice_number||invoice.invoice_number||"—")}</div></header><div class="table"><table><thead><tr><th>#</th><th>Medicine</th><th>Batch</th><th>Expiry</th><th>Paid</th><th>Free</th><th>PTR</th><th>MRP</th><th>GST</th><th>Total</th></tr></thead><tbody>${lines.map((x,i)=>`<tr><td>${i+1}</td><td>${s(x.medicines?.brand_name||"Medicine")}</td><td>${s(x.batch_number)}</td><td>${date(x.expiry_date+"T00:00:00")}</td><td>${n(x.quantity)}</td><td>${n(x.free_quantity)}</td><td>${m(x.purchase_rate)}</td><td>${m(x.mrp)}</td><td>${n(x.gst_percent)}%</td><td>${m(x.line_total)}</td></tr>`).join("")}</tbody></table></div><div class="purchase-invoice-totals"><span>Taxable <b>${m(invoice.taxable_amount)}</b></span> <span>GST <b>${m(invoice.gst_amount)}</b></span> <span>Total <b>${m(invoice.grand_total)}</b></span> <span>Paid <b>${m(invoice.amount_paid)}</b></span> <span>Outstanding <b>${m(invoice.outstanding_amount)}</b></span></div></article>`}
 async function viewInvoice(id){const [a,b]=await Promise.all([supabaseClient.from("purchase_invoices").select("*,suppliers(*)").eq("id",id).eq("pharmacy_id",pid).single(),supabaseClient.from("purchase_items").select("*,medicines(brand_name,generic_name)").eq("purchase_invoice_id",id).eq("pharmacy_id",pid).order("created_at")]);if(a.error)throw a.error;if(b.error)throw b.error;reportInvoiceMarkup=invoiceMarkup(a.data,b.data||[]);E("ViewContent").innerHTML=reportInvoiceMarkup;E("ViewPanel").hidden=false;E("ViewPanel").scrollIntoView({behavior:"smooth",block:"start"})}
 function printInvoice(){if(!reportInvoiceMarkup)return UI.toast("Open an invoice first.","warning");const w=window.open("","_blank");if(!w)return UI.toast("Allow pop-ups to print.","warning");w.document.write(`<!doctype html><html><head><title>Purchase Invoice</title><style>body{font-family:Arial;padding:20px}header,.purchase-invoice-totals{display:flex;justify-content:space-between;gap:14px;flex-wrap:wrap;margin-bottom:15px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:7px;font-size:12px;text-align:left}@page{size:A4;margin:12mm}</style></head><body>${reportInvoiceMarkup}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),200)}
 function returnValue(x){return n(first(x,["supplier_total_credit","return_amount"],0))}
 function apply(){const f=E("From").value,t=E("To").value,st=E("Filter").value,q=E("Search").value.trim().toLowerCase();visible=rows.filter(x=>{const d=dateKey(first(x,["purchase_date","invoice_date","created_at"])),pst=String(first(x,["payment_status"],"")).toLowerCase(),ist=String(first(x,["purchase_status","status"],"")).toLowerCase(),txt=[x.purchase_number,x.invoice_number,x.supplier_invoice_number,x.suppliers?.name,pst,ist].join(" ").toLowerCase();return(!f||d>=f)&&(!t||d<=t)&&(!st||(st==="cancelled"?ist==="cancelled":pst===st))&&(!q||txt.includes(q));});
 const posted=visible.filter(x=>String(first(x,["purchase_status","status"],"")).toLowerCase()!=="cancelled"),invoiceIds=new Set(posted.map(x=>x.id)),validReturns=returns.filter(x=>{const d=dateKey(x.return_date),status=String(x.return_status||"").toLowerCase();return invoiceIds.has(x.purchase_invoice_id)&&status!=="cancelled"&&(!f||d>=f)&&(!t||d<=t)}),returnByInvoice=new Map();validReturns.forEach(x=>returnByInvoice.set(x.purchase_invoice_id,n(returnByInvoice.get(x.purchase_invoice_id))+returnValue(x)));
 const gross=posted.reduce((a,x)=>a+n(first(x,["grand_total","net_amount","total_amount"],0)),0),returned=validReturns.reduce((a,x)=>a+returnValue(x),0),net=gross-returned,bal=posted.reduce((a,x)=>a+n(first(x,["outstanding_amount","balance_amount"],0)),0);
 E("Sum1Label").textContent="Gross Purchases";E("Sum1").textContent=m(gross);E("Sum2Label").textContent="Purchase Returns";E("Sum2").textContent=m(returned);E("Sum3Label").textContent="Net Purchases";E("Sum3").textContent=m(net);E("Sum4Label").textContent="Recorded Outstanding";E("Sum4").textContent=m(bal);E("Count").textContent=`${visible.length} rows`;
 E("Head").innerHTML="<tr><th>Date</th><th>Purchase</th><th>Supplier Invoice</th><th>Supplier</th><th>Taxable</th><th>Total GST</th><th>Gross Total</th><th>Returns</th><th>Net Purchase</th><th>Paid</th><th>Outstanding</th><th>Status</th><th>Action</th></tr>";
 E("Body").innerHTML=visible.length?visible.map(x=>{const returned=n(returnByInvoice.get(x.id)),cancelled=String(first(x,["purchase_status","status"],"")).toLowerCase()==="cancelled",gross=n(first(x,["grand_total","net_amount","total_amount"],0));return`<tr><td>${s(dateKey(first(x,["purchase_date","invoice_date","created_at"])))}</td><td><b>${s(first(x,["purchase_number","invoice_number"],"—"))}</b></td><td>${s(first(x,["supplier_invoice_number","invoice_number"],"—"))}</td><td>${s(x.suppliers?.name||"Supplier")}</td><td>${m(first(x,["taxable_amount"],0))}</td><td>${m(first(x,["gst_amount"],0))}</td><td>${m(gross)}</td><td>${m(returned)}</td><td><b>${m(cancelled?0:gross-returned)}</b></td><td>${m(first(x,["amount_paid"],0))}</td><td>${m(first(x,["outstanding_amount","balance_amount"],0))}</td><td>${s(first(x,["payment_status","purchase_status","status"],"—"))}</td><td><button type="button" data-view-purchase="${x.id}">View</button></td></tr>`}).join(""):'<tr><td colspan="13" class="empty">No purchases found.</td></tr>';E("Body").querySelectorAll("[data-view-purchase]").forEach(button=>button.onclick=()=>viewInvoice(button.dataset.viewPurchase).catch(e=>UI.toast(e.message,"error")));
 }

 function csv(){if(!visible.length)return UI.toast("No purchases to export.","warning");const f=E("From").value,t=E("To").value,validReturns=returns.filter(x=>String(x.return_status||"").toLowerCase()!=="cancelled"&&(!f||dateKey(x.return_date)>=f)&&(!t||dateKey(x.return_date)<=t)),returnByInvoice=new Map();validReturns.forEach(x=>returnByInvoice.set(x.purchase_invoice_id,n(returnByInvoice.get(x.purchase_invoice_id))+returnValue(x)));const esc=v=>`"${String(v??"").replaceAll('"','""')}"`,lines=[["Date","Purchase","Supplier Invoice","Supplier","Taxable","Total GST","Gross Total","Returns","Net Purchase","Paid","Outstanding","Status"].map(esc).join(","),...visible.map(x=>{const returned=n(returnByInvoice.get(x.id)),cancelled=String(first(x,["purchase_status","status"],"")).toLowerCase()==="cancelled",gross=n(first(x,["grand_total","net_amount","total_amount"],0));return[dateKey(first(x,["purchase_date","invoice_date","created_at"])),first(x,["purchase_number","invoice_number"]),first(x,["supplier_invoice_number","invoice_number"]),x.suppliers?.name||"",n(x.taxable_amount).toFixed(2),n(x.gst_amount).toFixed(2),gross.toFixed(2),returned.toFixed(2),(cancelled?0:gross-returned).toFixed(2),n(x.amount_paid).toFixed(2),n(first(x,["outstanding_amount","balance_amount"],0)).toFixed(2),first(x,["payment_status","purchase_status","status"])].map(esc).join(",")})];const b=new Blob([lines.join("\n")],{type:"text/csv"}),a=document.createElement("a"),u=URL.createObjectURL(b);a.href=u;a.download=`medvika-purchase-report-${f}-to-${t}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);}

 dates();["From","To","Filter"].forEach(x=>E(x).onchange=apply);E("Search").oninput=apply;E("Apply").onclick=apply;E("Export").onclick=csv;E("Refresh").onclick=()=>load().catch(e=>UI.toast(e.message,"error"));E("ViewClose").onclick=()=>{E("ViewPanel").hidden=true};E("ViewPrint").onclick=printInvoice;try{await load();}catch(e){UI.toast(e.message,"error");}
};