window.initComplianceRegistersModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id;
 let rows=[],editing=null;
 const norm=s=>String(s||"").toUpperCase().replace(/\b(IP|BP|USP|PH\.?EUR\.?)\b/g," ").replace(/\b\d+(\.\d+)?\s*(MG|MCG|G|ML|%|IU)\b/g," ").replace(/[^A-Z0-9]+/g," ").trim().replace(/\s+/g,"_");
 async function log(event,entity,id,description,metadata={}){await supabaseClient.from("compliance_audit_log").insert({pharmacy_id:pid,event_type:event,entity_type:entity,entity_id:id||null,description,metadata,actor_id:window.MedvikaAuth?.user?.id||null})}
 function render(){const q=$("crSearch").value.trim().toLowerCase(),list=rows.filter(x=>!q||`${x.display_name} ${x.generic_key}`.toLowerCase().includes(q));$("crBody").innerHTML=list.map(x=>`<tr><td>${UI.safe(x.display_name)}</td><td>${x.schedule_h1?"Yes":"—"}</td><td>${x.nrx?"Yes":"—"}</td><td>${x.schedule_x?"Yes":"—"}</td><td>${x.controlled_drug?"Yes":"—"}</td><td>${UI.safe(x.effective_from||"—")} → ${UI.safe(x.effective_to||"Open")}</td><td>${UI.safe(x.source_reference||"—")}</td><td><button data-edit="${x.id}">Edit</button></td></tr>`).join("")||'<tr><td colspan="8">No rules.</td></tr>';document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>open(rows.find(x=>x.id===b.dataset.edit)))}
 function open(x=null){editing=x?.id||null;$("crName").value=x?.display_name||"";$("crH1").checked=!!x?.schedule_h1;$("crNrx").checked=!!x?.nrx;$("crX").checked=!!x?.schedule_x;$("crControlled").checked=!!x?.controlled_drug;$("crFrom").value=x?.effective_from||"";$("crTo").value=x?.effective_to||"";$("crSource").value=x?.source_reference||"";$("crNotes").value=x?.notes||"";$("crModal").hidden=false}
 async function load(){const{data,error}=await supabaseClient.from("generic_compliance_rules").select("*").or(`pharmacy_id.is.null,pharmacy_id.eq.${pid}`).order("display_name");if(error)throw error;rows=data||[];render()}
 async function save(){const name=$("crName").value.trim();if(!name)return UI.toast("Generic / salt is required.","warning");const payload={pharmacy_id:pid,generic_key:norm(name),display_name:name,schedule_h1:$("crH1").checked,nrx:$("crNrx").checked,schedule_x:$("crX").checked,controlled_drug:$("crControlled").checked,effective_from:$("crFrom").value||null,effective_to:$("crTo").value||null,source_reference:$("crSource").value.trim()||null,notes:$("crNotes").value.trim()||null,is_active:true,updated_at:new Date().toISOString()};let r=editing?await supabaseClient.from("generic_compliance_rules").update(payload).eq("id",editing):await supabaseClient.from("generic_compliance_rules").insert(payload).select("id").single();if(r.error)return UI.toast(r.error.message,"error");const id=editing||r.data?.id;await log(editing?"RULE_UPDATED":"RULE_CREATED","generic_compliance_rule",id,`${name} compliance rule ${editing?"updated":"created"}`,payload);$("crModal").hidden=true;await load()}
 document.querySelectorAll("[data-route]").forEach(a=>a.onclick=()=>window.MedvikaRouter?.navigate?.(a.dataset.route));
 $("crSearch").oninput=render;$("crAdd").onclick=()=>open();$("crClose").onclick=()=>{$("crModal").hidden=true};$("crSave").onclick=save;try{await load()}catch(e){UI.toast(e.message,"error")}
};