window.initReturnReportModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id;
 const n=v=>Number.isFinite(Number(v))?Number(v):0,m=v=>UI.money(n(v)),s=v=>UI.safe(v??"");let rows=[],visible=[];if(!pid){UI.toast("Pharmacy profile not available.","error");return;}const P="rr",E=x=>$(P+x),first=(o,ks,d="")=>{for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null&&o[k]!=="")return o[k];return d;};
 function dateKey(value){if(!value)return "";const raw=String(value);if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return "";const y=d.getFullYear(),mo=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${mo}-${day}`;}
 function displayDate(value){const key=dateKey(value);if(!key)return "—";const [y,mo,d]=key.split("-");return `${d}/${mo}/${y}`;}
 function dates(){const d=new Date(),f=new Date(d.getFullYear(),d.getMonth(),1);E("From").value=dateKey(f);E("To").value=dateKey(d);}
 async function safeTable(table,select="*"){const r=await supabaseClient.from(table).select(select).eq("pharmacy_id",pid).limit(30000);if(r.error){console.warn(table,r.error);return [];}return r.data||[];}
 async function load(){const [sr,pr]=await Promise.all([safeTable("sales_returns","*,sales_invoices(invoice_number,patient_name,customers(full_name))"),safeTable("purchase_returns","*,suppliers(name),purchase_invoices(purchase_number,supplier_invoice_number)")]);rows=[];(sr||[]).forEach(x=>rows.push({date:first(x,["return_date","created_at"]),type:"SALES_RETURN",reference:first(x,["return_number"],"—"),party:x.sales_invoices?.customers?.full_name||x.sales_invoices?.patient_name||"Walk-in",invoice:x.sales_invoices?.invoice_number||"—",amount:n(first(x,["refund_amount","grand_total","total_amount","net_amount"],0)),mode:first(x,["refund_mode","refund_method"],""),status:first(x,["return_status","status"],"posted")}));(pr||[]).forEach(x=>rows.push({date:first(x,["return_date","created_at"]),type:"PURCHASE_RETURN",reference:first(x,["return_number","purchase_return_number"],"—"),party:x.suppliers?.name||"Supplier",invoice:x.purchase_invoices?.purchase_number||x.purchase_invoices?.supplier_invoice_number||first(x,["supplier_invoice_number","purchase_invoice_number"],"—"),amount:n(first(x,["supplier_total_credit","return_amount","grand_total","total_amount","net_amount","refund_amount"],0)),mode:first(x,["settlement_mode","refund_mode"],""),status:first(x,["return_status","status"],"posted")}));rows=rows.filter(x=>String(x.status||"posted").toLowerCase()!=="cancelled");rows.sort((a,b)=>dateKey(b.date).localeCompare(dateKey(a.date)));apply();}
 function apply(){const f=E("From").value,t=E("To").value,typ=E("Filter").value,q=E("Search").value.trim().toLowerCase();visible=rows.filter(x=>{const d=dateKey(x.date),txt=[x.type,x.reference,x.party,x.invoice,x.mode,x.status].join(" ").toLowerCase();return(!f||d>=f)&&(!t||d<=t)&&(!typ||x.type===typ)&&(!q||txt.includes(q));});const sales=visible.filter(x=>x.type==="SALES_RETURN").reduce((a,x)=>a+x.amount,0),purch=visible.filter(x=>x.type==="PURCHASE_RETURN").reduce((a,x)=>a+x.amount,0);E("Sum1Label").textContent="Total Returns";E("Sum1").textContent=visible.length;E("Sum2Label").textContent="Sales Returns";E("Sum2").textContent=m(sales);E("Sum3Label").textContent="Purchase Returns";E("Sum3").textContent=m(purch);E("Sum4Label").textContent="Combined Return Value";E("Sum4").textContent=m(sales+purch);E("Count").textContent=`${visible.length} rows`;E("Head").innerHTML="<tr><th>Date</th><th>Type</th><th>Reference</th><th>Party</th><th>Invoice</th><th>Mode</th><th>Amount</th><th>Status</th></tr>";E("Body").innerHTML=visible.length?visible.map(x=>`<tr><td>${displayDate(x.date)}</td><td>${s(x.type.replaceAll("_"," "))}</td><td><b>${s(x.reference)}</b></td><td>${s(x.party)}</td><td>${s(x.invoice)}</td><td>${s(x.mode||"—")}</td><td>${m(x.amount)}</td><td>${s(x.status)}</td></tr>`).join(""):'<tr><td colspan="8" class="empty">No return rows found.</td></tr>';}
 function csv(){if(!visible.length)return UI.toast("No return data to export.","warning");const esc=v=>`"${String(v??"").replaceAll('"','""')}"`,lines=[["Date","Type","Reference","Party","Invoice","Mode","Amount","Status"].map(esc).join(","),...visible.map(x=>[dateKey(x.date),x.type,x.reference,x.party,x.invoice,x.mode,x.amount.toFixed(2),x.status].map(esc).join(","))];const b=new Blob([lines.join("\n")],{type:"text/csv"}),a=document.createElement("a"),u=URL.createObjectURL(b);a.href=u;a.download="medvika-return-report.csv";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);}
 dates();["From","To","Filter"].forEach(x=>E(x).onchange=apply);E("Search").oninput=apply;E("Apply").onclick=apply;E("Export").onclick=csv;E("Refresh").onclick=()=>load().catch(e=>UI.toast(e.message,"error"));try{await load();}catch(e){UI.toast(e.message,"error");}
};