window.initSalesReportModule=async function(){
 const UI=window.MedvikaUI,$=id=>document.getElementById(id),pid=window.MedvikaAuth?.profile?.pharmacy_id;
 const n=v=>Number.isFinite(Number(v))?Number(v):0,m=v=>UI.money(n(v)),s=v=>UI.safe(v??"");
 let rows=[],returns=[],visible=[];
 if(!pid){UI.toast("Pharmacy profile not available.","error");return;}
 const P="sr",E=x=>$(P+x),first=(o,ks,d="")=>{for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null&&o[k]!=="")return o[k];return d;};
 function dates(){const d=new Date(),f=new Date(d.getFullYear(),d.getMonth(),1),L=x=>new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10);E("From").value=L(f);E("To").value=L(d);}
 function dateKey(v){const raw=String(v||"");if(!raw)return"";if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=new Date(raw);return Number.isNaN(d.getTime())?raw.slice(0,10):new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
 async function load(){const [salesResult,returnResult]=await Promise.all([supabaseClient.from("sales_invoices").select("*,customers(full_name,mobile)").eq("pharmacy_id",pid).order("invoice_date",{ascending:false}).limit(30000),supabaseClient.from("sales_returns").select("id,sales_invoice_id,return_date,refund_amount,return_status").eq("pharmacy_id",pid).limit(30000)]);if(salesResult.error)throw salesResult.error;if(returnResult.error)throw returnResult.error;rows=salesResult.data||[];returns=returnResult.data||[];apply();}
 function apply(){const f=E("From").value,t=E("To").value,st=E("Filter").value,q=E("Search").value.trim().toLowerCase();
 visible=rows.filter(x=>{const d=dateKey(first(x,["invoice_date","created_at"])),pst=String(first(x,["payment_status"],"")).toLowerCase(),ist=String(first(x,["invoice_status"],"")).toLowerCase(),txt=[x.invoice_number,x.customers?.full_name,x.patient_name,pst,ist].join(" ").toLowerCase();return(!f||d>=f)&&(!t||d<=t)&&(!st||(st==="cancelled"?ist==="cancelled":pst===st))&&(!q||txt.includes(q));});
 const posted=visible.filter(x=>String(x.invoice_status).toLowerCase()!=="cancelled"),invoiceIds=new Set(posted.map(x=>x.id)),validReturns=returns.filter(x=>{const d=dateKey(x.return_date),status=String(x.return_status||"").toLowerCase();return invoiceIds.has(x.sales_invoice_id)&&status!=="cancelled"&&(!f||d>=f)&&(!t||d<=t)}),returnByInvoice=new Map();validReturns.forEach(x=>returnByInvoice.set(x.sales_invoice_id,n(returnByInvoice.get(x.sales_invoice_id))+n(x.refund_amount)));
 const gross=posted.reduce((a,x)=>a+n(x.grand_total),0),returned=validReturns.reduce((a,x)=>a+n(x.refund_amount),0),net=gross-returned,bal=posted.reduce((a,x)=>a+n(x.balance_amount),0);
 E("Sum1Label").textContent="Gross Sales";E("Sum1").textContent=m(gross);E("Sum2Label").textContent="Sales Returns";E("Sum2").textContent=m(returned);E("Sum3Label").textContent="Net Sales";E("Sum3").textContent=m(net);E("Sum4Label").textContent="Outstanding";E("Sum4").textContent=m(bal);E("Count").textContent=`${visible.length} rows`;
 E("Head").innerHTML="<tr><th>Date</th><th>Invoice</th><th>Customer</th><th>Gross Total</th><th>Returns</th><th>Net Sale</th><th>Paid</th><th>Balance</th><th>Payment</th><th>Invoice Status</th></tr>";
 E("Body").innerHTML=visible.length?visible.map(x=>{const returned=n(returnByInvoice.get(x.id)),cancelled=String(x.invoice_status).toLowerCase()==="cancelled",gross=n(x.grand_total),net=cancelled?0:gross-returned;return`<tr><td>${UI.safe(dateKey(first(x,["invoice_date","created_at"])))}</td><td><b>${s(x.invoice_number)}</b></td><td>${s(x.customers?.full_name||x.patient_name||"Walk-in")}</td><td>${m(gross)}</td><td>${m(returned)}</td><td><b>${m(net)}</b></td><td>${m(x.amount_paid)}</td><td>${m(x.balance_amount)}</td><td>${s(x.payment_status)}</td><td>${s(x.invoice_status)}</td></tr>`}).join(""):'<tr><td colspan="10" class="empty">No sales found.</td></tr>';
 }

 function csv(){if(!visible.length)return UI.toast("No sales to export.","warning");const f=E("From").value,t=E("To").value,validReturns=returns.filter(x=>String(x.return_status||"").toLowerCase()!=="cancelled"&&(!f||dateKey(x.return_date)>=f)&&(!t||dateKey(x.return_date)<=t)),returnByInvoice=new Map();validReturns.forEach(x=>returnByInvoice.set(x.sales_invoice_id,n(returnByInvoice.get(x.sales_invoice_id))+n(x.refund_amount)));const esc=v=>`"${String(v??"").replaceAll('"','""')}"`,lines=[["Date","Invoice","Customer","Gross Total","Returns","Net Sale","Paid","Balance","Payment Status","Invoice Status"].map(esc).join(","),...visible.map(x=>{const returned=n(returnByInvoice.get(x.id)),cancelled=String(x.invoice_status).toLowerCase()==="cancelled",gross=n(x.grand_total);return[dateKey(first(x,["invoice_date","created_at"])),x.invoice_number,x.customers?.full_name||x.patient_name||"Walk-in",gross.toFixed(2),returned.toFixed(2),(cancelled?0:gross-returned).toFixed(2),n(x.amount_paid).toFixed(2),n(x.balance_amount).toFixed(2),x.payment_status,x.invoice_status].map(esc).join(",")})];const b=new Blob([lines.join("\n")],{type:"text/csv"}),a=document.createElement("a"),u=URL.createObjectURL(b);a.href=u;a.download=`medvika-sales-report-${f}-to-${t}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);}

 dates();["From","To","Filter"].forEach(x=>E(x).onchange=apply);E("Search").oninput=apply;E("Apply").onclick=apply;E("Export").onclick=csv;E("Refresh").onclick=()=>load().catch(e=>UI.toast(e.message,"error"));try{await load();}catch(e){UI.toast(e.message,"error");}
};