window.initSupplierLedgerModule=async function(){
  const UI=window.MedvikaUI;
  const $=id=>document.getElementById(id);
  const toast=(m,t="success")=>UI.toast(m,t==="danger"?"error":t);
  const pid=window.MedvikaAuth.profile?.pharmacy_id;
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const money=v=>UI.money(n(v));
  const safe=v=>UI.safe(v??"");
  let suppliers=[],purchases=[],payments=[],purchasePayments=[],returns=[],selectedSupplier=null,currentLedger=[];
  if(!pid){toast("Pharmacy profile not available.","danger");return;}
  function supplierName(s){return s?.name||"Supplier";}
  function localInput(v=null){const d=v?new Date(v):new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
  function dateKey(value){if(!value)return "";const raw=String(value);if(/^\d{4}-\d{2}-\d{2}$/.test(raw))return raw;const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return "";const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`;}
  function displayDate(value){const key=dateKey(value);if(!key)return "—";const [y,m,d]=key.split("-");return `${d}/${m}/${y}`;}
  function activePurchase(p){const status=String(p.purchase_status||p.invoice_status||"").toLowerCase();return status!=="cancelled";}
  function activeReturn(r){const status=String(r.return_status||"").toLowerCase();return status!=="cancelled";}
  function returnCredit(r){return n(r.supplier_total_credit||r.return_amount||0);}
  async function loadAll(){
    const [s,p,sp,pp,pr]=await Promise.all([
      supabaseClient.from("suppliers").select("*").eq("pharmacy_id",pid).order("name").limit(5000),
      supabaseClient.from("purchase_invoices").select("*").eq("pharmacy_id",pid).order("purchase_date",{ascending:true}).limit(20000),
      supabaseClient.from("supplier_payments").select("*").eq("pharmacy_id",pid).order("payment_date",{ascending:true}).limit(20000),
      supabaseClient.from("purchase_payments").select("*").eq("pharmacy_id",pid).order("payment_date",{ascending:true}).limit(20000),
      supabaseClient.from("purchase_returns").select("*").eq("pharmacy_id",pid).order("return_date",{ascending:true}).limit(20000)
    ]);
    const err=[s,p,sp,pp,pr].find(x=>x.error)?.error;if(err)throw err;
    suppliers=(s.data||[]).filter(x=>x.is_active!==false);purchases=p.data||[];payments=sp.data||[];purchasePayments=pp.data||[];returns=pr.data||[];fillSuppliers();renderSelected();
  }
  function fillSuppliers(){const select=$("supplierLedgerSupplier"),old=select.value;select.innerHTML='<option value="">Select supplier</option>'+suppliers.map(s=>`<option value="${s.id}">${safe(supplierName(s))}${s.supplier_code?` — ${safe(s.supplier_code)}`:""}</option>`).join("");if(old&&suppliers.some(s=>s.id===old))select.value=old;else if(suppliers.length===1)select.value=suppliers[0].id;}
  function filteredByDate(rows,dateField){const from=$("supplierLedgerFrom").value,to=$("supplierLedgerTo").value;return rows.filter(r=>{const d=dateKey(r[dateField]);return(!from||d>=from)&&(!to||d<=to);});}
  function buildLedger(supplier){
    const opening=n(supplier.opening_balance);const p=filteredByDate(purchases.filter(x=>x.supplier_id===supplier.id&&activePurchase(x)),"purchase_date");const sp=filteredByDate(payments.filter(x=>x.supplier_id===supplier.id),"payment_date");const purchaseIds=new Set(purchases.filter(x=>x.supplier_id===supplier.id&&activePurchase(x)).map(x=>x.id));const ip=filteredByDate(purchasePayments.filter(x=>purchaseIds.has(x.purchase_invoice_id)),"payment_date");const pr=filteredByDate(returns.filter(x=>x.supplier_id===supplier.id&&activeReturn(x)),"return_date");const entries=[];const from=$("supplierLedgerFrom").value;
    if(!from)entries.push({date:"",sortDate:"0000-00-00",type:"OPENING",reference:"Opening Balance",description:"Supplier opening balance",debit:opening>0?opening:0,credit:opening<0?Math.abs(opening):0});
    p.forEach(x=>entries.push({date:x.purchase_date||x.invoice_date,sortDate:x.purchase_date||x.invoice_date||"",type:"PURCHASE",reference:x.purchase_number||x.supplier_invoice_number||x.invoice_number||"—",description:x.supplier_invoice_number?`Supplier invoice ${x.supplier_invoice_number}`:"Purchase invoice",debit:n(x.grand_total),credit:0}));
    ip.forEach(x=>entries.push({date:x.payment_date||x.created_at,sortDate:x.payment_date||x.created_at||"",type:"PURCHASE PAYMENT",reference:x.transaction_reference||"At purchase",description:"Payment recorded with purchase invoice",debit:0,credit:n(x.amount)}));
    sp.forEach(x=>entries.push({date:x.payment_date,sortDate:x.payment_date||"",type:"PAYMENT",reference:x.payment_number||x.reference_number||"—",description:x.reference_number?`Payment ref ${x.reference_number}`:"Supplier payment",debit:0,credit:n(x.amount)}));
    pr.forEach(x=>{const credit=returnCredit(x);if(credit<=0)return;const reason=x.reason||x.return_reason||"Purchase return / supplier credit";const cn=x.supplier_cn_number||x.debit_note_number;entries.push({date:x.return_date||x.supplier_cn_date,sortDate:x.return_date||x.supplier_cn_date||"",type:"CREDIT NOTE",reference:x.return_number||cn||"—",description:cn?`Supplier CN ${cn} — ${reason}`:reason,debit:0,credit});});
    entries.sort((a,b)=>String(a.sortDate).localeCompare(String(b.sortDate))||a.type.localeCompare(b.type));let balance=from?calculateBalanceBefore(supplier,from):0;entries.forEach(e=>{balance+=n(e.debit)-n(e.credit);e.balance=balance;});return{entries,purchases:p,payments:[...ip,...sp],returns:pr};
  }
  function calculateBalanceBefore(supplier,from){let bal=n(supplier.opening_balance);purchases.filter(x=>x.supplier_id===supplier.id&&activePurchase(x)&&dateKey(x.purchase_date||x.invoice_date)<from).forEach(x=>bal+=n(x.grand_total));const priorPurchaseIds=new Set(purchases.filter(x=>x.supplier_id===supplier.id&&activePurchase(x)).map(x=>x.id));purchasePayments.filter(x=>priorPurchaseIds.has(x.purchase_invoice_id)&&dateKey(x.payment_date||x.created_at)<from).forEach(x=>bal-=n(x.amount));payments.filter(x=>x.supplier_id===supplier.id&&dateKey(x.payment_date)<from).forEach(x=>bal-=n(x.amount));returns.filter(x=>x.supplier_id===supplier.id&&activeReturn(x)&&dateKey(x.return_date||x.supplier_cn_date)<from).forEach(x=>bal-=returnCredit(x));return bal;}
  function renderSelected(){
    const sid=$("supplierLedgerSupplier").value;selectedSupplier=suppliers.find(x=>x.id===sid)||null;
    if(!selectedSupplier){["supplierOpeningBalance","supplierTotalPurchases","supplierTotalPayments","supplierTotalCredits","supplierAccountBalance","supplierInvoiceOutstanding","supplierOverdueAmount"].forEach(id=>$(id).textContent=money(0));$("supplierOutstandingTable").innerHTML='<tr><td colspan="8" class="empty">Select a supplier.</td></tr>';$("supplierOutstandingCards").innerHTML="";$("supplierLedgerTable").innerHTML='<tr><td colspan="7" class="empty">Select a supplier.</td></tr>';$("supplierLedgerCards").innerHTML="";$("supplierOutstandingCount").textContent="0 invoices";$("supplierLedgerCount").textContent="0 entries";currentLedger=[];return;}
    const built=buildLedger(selectedSupplier);currentLedger=built.entries;const allPurchases=purchases.filter(x=>x.supplier_id===selectedSupplier.id&&activePurchase(x));const totalPurchases=built.purchases.reduce((s,x)=>s+n(x.grand_total),0),totalPayments=built.payments.reduce((s,x)=>s+n(x.amount),0),totalCredits=built.returns.reduce((s,x)=>s+returnCredit(x),0),periodOpening=$("supplierLedgerFrom").value?calculateBalanceBefore(selectedSupplier,$("supplierLedgerFrom").value):n(selectedSupplier.opening_balance),accountBalance=periodOpening+totalPurchases-totalPayments-totalCredits,outstanding=allPurchases.filter(x=>n(x.outstanding_amount)>0),outstandingTotal=outstanding.reduce((s,x)=>s+n(x.outstanding_amount),0),today=dateKey(new Date()),overdue=outstanding.filter(x=>x.due_date&&x.due_date<today).reduce((s,x)=>s+n(x.outstanding_amount),0);
    $("supplierOpeningBalance").textContent=money(periodOpening);$("supplierTotalPurchases").textContent=money(totalPurchases);$("supplierTotalPayments").textContent=money(totalPayments);$("supplierTotalCredits").textContent=money(totalCredits);$("supplierAccountBalance").textContent=money(accountBalance);$("supplierInvoiceOutstanding").textContent=money(outstandingTotal);$("supplierOverdueAmount").textContent=money(overdue);renderOutstanding(outstanding);renderLedger(built.entries);
  }
  function renderOutstanding(rows){
    $("supplierOutstandingCount").textContent=`${rows.length} invoice${rows.length===1?"":"s"}`;const sorted=rows.slice().sort((a,b)=>String(a.due_date||a.purchase_date||"").localeCompare(String(b.due_date||b.purchase_date||"")));
    $("supplierOutstandingTable").innerHTML=sorted.length?sorted.map(x=>`<tr><td><b>${safe(x.purchase_number||"—")}</b></td><td>${safe(x.supplier_invoice_number||x.invoice_number||"—")}</td><td>${x.purchase_date?displayDate(x.purchase_date):"—"}</td><td>${x.due_date?displayDate(x.due_date):"—"}</td><td>${money(x.grand_total)}</td><td>${money(x.amount_paid)}</td><td><b>${money(x.outstanding_amount)}</b></td><td>${safe(String(x.payment_status||"unpaid").toUpperCase())}</td></tr>`).join(""):'<tr><td colspan="8" class="empty">No outstanding purchase invoices.</td></tr>';
    $("supplierOutstandingCards").innerHTML=sorted.length?sorted.map(x=>`<article class="mobile-record-card"><div class="mobile-record-top"><strong>${safe(x.purchase_number||"Purchase")}</strong><span class="mobile-status">${safe(String(x.payment_status||"unpaid").replaceAll("_"," ").toUpperCase())}</span></div><div class="mobile-record-sub">Supplier invoice: ${safe(x.supplier_invoice_number||x.invoice_number||"—")}</div><div class="mobile-record-grid"><div><small>Purchase</small><strong>${x.purchase_date?displayDate(x.purchase_date):"—"}</strong></div><div><small>Due</small><strong>${x.due_date?displayDate(x.due_date):"—"}</strong></div><div><small>Total</small><strong>${money(x.grand_total)}</strong></div><div><small>Paid</small><strong>${money(x.amount_paid)}</strong></div></div><div class="mobile-record-total"><span>Outstanding</span><strong>${money(x.outstanding_amount)}</strong></div></article>`).join(""):'<div class="mobile-empty">No outstanding purchase invoices.</div>';
  }
  function renderLedger(rows){
    $("supplierLedgerCount").textContent=`${rows.length} entr${rows.length===1?"y":"ies"}`;$("supplierLedgerTable").innerHTML=rows.length?rows.map(x=>`<tr><td>${x.date?displayDate(x.date):"—"}</td><td><span class="ledger-type">${safe(x.type)}</span></td><td><b>${safe(x.reference)}</b></td><td>${safe(x.description)}</td><td>${x.debit?money(x.debit):"—"}</td><td>${x.credit?money(x.credit):"—"}</td><td><b>${money(x.balance)}</b></td></tr>`).join(""):'<tr><td colspan="7" class="empty">No ledger transactions for this period.</td></tr>';
    $("supplierLedgerCards").innerHTML=rows.length?rows.map(x=>`<article class="mobile-record-card ledger-mobile-card"><div class="mobile-record-top"><span class="ledger-type">${safe(x.type)}</span><strong>${x.date?displayDate(x.date):"Opening"}</strong></div><div class="mobile-record-sub"><strong>${safe(x.reference)}</strong><br>${safe(x.description)}</div><div class="mobile-record-grid"><div><small>Debit</small><strong>${x.debit?money(x.debit):"—"}</strong></div><div><small>Credit</small><strong>${x.credit?money(x.credit):"—"}</strong></div></div><div class="mobile-record-total"><span>Balance</span><strong>${money(x.balance)}</strong></div></article>`).join(""):'<div class="mobile-empty">No ledger transactions for this period.</div>';
  }
  function fillPaymentInvoices(){const select=$("supplierPaymentInvoice"),outstanding=purchases.filter(x=>selectedSupplier&&x.supplier_id===selectedSupplier.id&&activePurchase(x)&&n(x.outstanding_amount)>0).sort((a,b)=>String(a.due_date||a.purchase_date||a.invoice_date||"").localeCompare(String(b.due_date||b.purchase_date||b.invoice_date||"")));select.innerHTML='<option value="">FIFO — Oldest invoices first (bulk payment)</option>'+outstanding.map(x=>`<option value="${x.id}" data-outstanding="${n(x.outstanding_amount)}">${safe(x.purchase_number||x.supplier_invoice_number||"Purchase")} — Outstanding ${money(x.outstanding_amount)}</option>`).join("");}
  function openPayment(){if(!selectedSupplier){toast("Select a supplier first.","warning");return;}$("supplierPaymentSupplierName").value=supplierName(selectedSupplier);fillPaymentInvoices();$("supplierPaymentDate").value=localInput();$("supplierPaymentAmount").value="";$("supplierPaymentMode").value="BANK_TRANSFER";$("supplierPaymentReference").value="";$("supplierPaymentNotes").value="";$("supplierPaymentPanel").hidden=false;$("supplierPaymentPanel").scrollIntoView({behavior:"smooth",block:"start"});}
  async function savePayment(e){e.preventDefault();if(!selectedSupplier){toast("Select a supplier first.","warning");return;}const amount=n($("supplierPaymentAmount").value);if(amount<=0){toast("Enter a valid payment amount.","warning");return;}const btn=$("saveSupplierPaymentButton");btn.disabled=true;btn.textContent="Recording...";try{const{data,error}=await supabaseClient.rpc("record_supplier_payment_v2",{p_supplier_id:selectedSupplier.id,p_purchase_invoice_id:$("supplierPaymentInvoice").value||null,p_payment_date:new Date($("supplierPaymentDate").value).toISOString(),p_amount:amount,p_payment_mode:$("supplierPaymentMode").value,p_reference_number:$("supplierPaymentReference").value.trim()||null,p_notes:$("supplierPaymentNotes").value.trim()||null});if(error)throw error;const unallocated=n(data?.unallocated_amount);toast(unallocated>0?`Payment recorded. ${money(unallocated)} remains unallocated.`:`Supplier payment recorded (${data?.allocation_mode==="INVOICE"?"specific invoice":"FIFO"}).`);$("supplierPaymentPanel").hidden=true;await loadAll();$("supplierLedgerSupplier").value=selectedSupplier.id;renderSelected();}catch(err){toast(err.message||"Supplier payment could not be recorded.","danger")}finally{btn.disabled=false;btn.textContent="Record Payment"}}
  function exportCsv(){if(!selectedSupplier){toast("Select a supplier first.","warning");return;}const esc=v=>`"${String(v??"").replaceAll('"','""')}"`;const lines=[["Date","Type","Reference","Description","Debit","Credit","Balance"].map(esc).join(","),...currentLedger.map(x=>[(x.date?dateKey(x.date):""),x.type,x.reference,x.description,n(x.debit).toFixed(2),n(x.credit).toFixed(2),n(x.balance).toFixed(2)].map(esc).join(","))];const blob=new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`supplier-ledger-${supplierName(selectedSupplier).replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-${dateKey(new Date())}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(a.href)}
  $("supplierLedgerSupplier").onchange=renderSelected;$("supplierLedgerApplyButton").onclick=renderSelected;$("supplierLedgerFrom").onchange=renderSelected;$("supplierLedgerTo").onchange=renderSelected;$("supplierLedgerExportButton").onclick=exportCsv;$("supplierLedgerPaymentButton").onclick=openPayment;$("closeSupplierPaymentButton").onclick=()=>{$("supplierPaymentPanel").hidden=true};$("supplierPaymentForm").onsubmit=savePayment;
  $("refreshSupplierLedgerButton").onclick=async()=>{try{const sid=$("supplierLedgerSupplier").value;await loadAll();if(sid)$("supplierLedgerSupplier").value=sid;renderSelected();toast("Supplier ledger refreshed.")}catch(err){toast(err.message,"danger")}};
  try{await loadAll();if($("supplierLedgerSupplier").value)renderSelected()}catch(err){toast("Supplier Ledger could not load: "+err.message,"danger")}
};