
const URL="https://etevzodzxhsdwidtrmwv.supabase.co",KEY="sb_publishable_iKWBOAxrWTZfU6Qb5PYd5Q_0y80GEOw";const sb=supabase.createClient(URL,KEY);const $=id=>document.getElementById(id);
let customers=[],currentCustomer=null,currentAudit=null,audits=[];
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}function msg(t){$("msg").textContent=t||"";}
$("loginBtn").onclick=async()=>{const {error}=await sb.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMsg").textContent=error.message;return;}const {data:isAdmin}=await sb.rpc("medvika_is_audit_admin");if(!isAdmin){$("loginMsg").textContent="This login is not registered as a Medvika Audit Admin.";return;}$("loginCard").hidden=true;$("adminArea").hidden=false;$("logoutBtn").hidden=false;await loadCustomers();};
$("logoutBtn").onclick=async()=>{await sb.auth.signOut();location.reload();};
async function loadCustomers(){const {data,error}=await sb.rpc("medvika_admin_customer_list");if(error){msg(error.message);return;}customers=data||[];$("customerList").innerHTML=customers.map(c=>`<div class="audit-row"><div><strong>${esc(c.business_name)} — ${esc(c.full_name)}</strong><br><small>${esc(c.email)} • ${esc(c.plan_name||"No plan")} • ${esc(c.status)} • Access ${esc(c.access_until||"—")}</small></div><button class="btn secondary open-client" data-id="${c.customer_id}">Manage</button></div>`).join("")||'<p class="muted">No customers.</p>';document.querySelectorAll(".open-client").forEach(b=>b.onclick=()=>openClient(b.dataset.id));}
async function openClient(id){currentCustomer=customers.find(c=>c.customer_id===id);$("clientPanel").hidden=false;$("clientTitle").textContent=currentCustomer?`${currentCustomer.business_name} — ${currentCustomer.full_name}`:"Customer";const {data,error}=await sb.rpc("medvika_customer_audits",{p_customer_id:id});if(error){msg(error.message);return;}audits=data||[];$("clientAudits").innerHTML=audits.map(a=>`<div class="audit-row"><div><strong>${esc(a.project_code)} — ${esc(a.project_name)}</strong><br><small>${esc(a.location||"")} • ${esc(a.audit_date||"")} • ${esc(a.status)}</small></div><button class="btn secondary open-audit" data-id="${a.audit_id}">Manage Audit</button></div>`).join("")||'<p class="muted">No audits assigned.</p>';document.querySelectorAll(".open-audit").forEach(b=>b.onclick=()=>openAudit(b.dataset.id));}
$("createAuditBtn").onclick=()=>{$("modal").hidden=false;};$("cancelModal").onclick=()=>{$("modal").hidden=true;};
$("confirmAudit").onclick=async()=>{const {data,error}=await sb.rpc("medvika_create_customer_audit",{p_customer_id:currentCustomer.customer_id,p_project_name:$("newAuditName").value,p_location:$("newAuditLocation").value,p_audit_date:$("newAuditDate").value,p_expected_items:Number($("newAuditItems").value||20000)});if(error){msg(error.message);return;}$("modal").hidden=true;await openClient(currentCustomer.customer_id);await openAudit(data);};
async function openAudit(id){currentAudit=audits.find(a=>a.audit_id===id)||{audit_id:id};$("auditManage").hidden=false;$("adminAuditTitle").textContent=`${currentAudit.project_code||""} — ${currentAudit.project_name||"Audit"}`;await Promise.all([loadSummary(),loadZones(),loadTeams()]);}
async function loadSummary(){const {data,error}=await sb.rpc("medvika_customer_audit_summary",{p_customer_id:currentCustomer.customer_id,p_audit_id:currentAudit.audit_id});if(error){msg(error.message);return;}const r=data?.[0]||{};$("adminSummary").innerHTML=[["Count Lines",r.total_count_lines],["Variance",r.variance_lines],["Expired",r.expired_lines],["Near Expiry",r.near_expiry_lines],["Damaged",r.damaged_lines],["Progress",Number(r.progress_percent||0).toFixed(1)+"%"]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]??0}</strong></div>`).join("");}
async function loadZones(){const {data,error}=await sb.rpc("medvika_customer_zones",{p_customer_id:currentCustomer.customer_id,p_audit_id:currentAudit.audit_id});if(error){msg(error.message);return;}const rows=data||[];$("zoneList").innerHTML=rows.map(z=>`<div class="item-row"><div><strong>${esc(z.zone_code)} — ${esc(z.zone_name)}</strong><br><small>${esc(z.category||"")}</small></div></div>`).join("")||'<p class="muted">No zones.</p>';$("teamZone").innerHTML=rows.map(z=>`<option value="${z.id}">${esc(z.zone_code)} — ${esc(z.zone_name)}</option>`).join("");}
$("addZoneBtn").onclick=async()=>{const {error}=await sb.rpc("medvika_manage_zone",{p_customer_id:currentCustomer.customer_id,p_audit_id:currentAudit.audit_id,p_zone_name:$("zoneName").value,p_category:$("zoneCategory").value,p_zone_id:null});if(error){msg(error.message);return;}$("zoneName").value="";$("zoneCategory").value="";await loadZones();};
async function loadTeams(){const {data,error}=await sb.rpc("medvika_customer_teams",{p_customer_id:currentCustomer.customer_id,p_audit_id:currentAudit.audit_id});if(error){msg(error.message);return;}const rows=data||[];$("teamList").innerHTML=rows.map(t=>`<div class="item-row"><div><strong>${esc(t.team_code)} — ${esc(t.team_name||"")}</strong><br><small>${esc(t.zone_code||"")} ${esc(t.zone_name||"")} • Login ${esc(t.login_code||"—")}</small></div><button class="btn secondary reset-pin" data-id="${t.team_id}">Reset PIN</button></div>`).join("")||'<p class="muted">No teams.</p>';document.querySelectorAll(".reset-pin").forEach(b=>b.onclick=async()=>{const pin=prompt("New PIN:");if(!pin)return;const {error}=await sb.rpc("medvika_reset_customer_team_pin",{p_customer_id:currentCustomer.customer_id,p_audit_id:currentAudit.audit_id,p_team_id:b.dataset.id,p_new_pin:pin});msg(error?error.message:"PIN reset.");});}
$("addTeamBtn").onclick=async()=>{const {error}=await sb.rpc("medvika_create_customer_team",{p_customer_id:currentCustomer.customer_id,p_audit_id:currentAudit.audit_id,p_zone_id:$("teamZone").value,p_team_name:$("teamName").value,p_login_code:$("teamLoginCode").value,p_pin:$("teamPin").value,p_can_add_unlisted:true});if(error){msg(error.message);return;}$("teamName").value="";$("teamLoginCode").value="";$("teamPin").value="";await loadTeams();};
(async()=>{const {data}=await sb.auth.getSession();if(data.session){const {data:a}=await sb.rpc("medvika_is_audit_admin");if(a){$("loginCard").hidden=true;$("adminArea").hidden=false;$("logoutBtn").hidden=false;loadCustomers();}}})();
